from PyQt5.QtWidgets import (
    QWidget,
    QVBoxLayout,
    QHBoxLayout,
    QTableWidget,
    QTableWidgetItem,
    QPushButton,
    QFileDialog,
    QInputDialog,
    QMessageBox,
    QLineEdit,
    QDateEdit,
    QAbstractItemView,
    QHeaderView,
    QLabel,
    QComboBox,
    QDialog,
    QDialogButtonBox,
    QCheckBox,
)
from PyQt5.QtCore import QDate, Qt, QUrl
from PyQt5.QtGui import QPixmap, QDesktopServices
import os
import re

from ticket_pdf import generar_ticket_personalizado
from factura_sv import (
    generar_factura_electronica_pdf,
    generar_nota_credito_pdf,
    generar_nota_debito_pdf,
    generar_nota_remision_pdf,
)
from dte import (
    generar_nota_credito_json,
    generar_nota_debito_json,
    generar_nota_remision_json,
    transmitir_dte,
)
from utils.monto import monto_a_texto_sv
from utils.docs import get_document_paths, build_invoice_json
import uuid
from utils.email_sender import EmailSender
from paths import DATOS_NEGOCIO_PATH
import tempfile
import subprocess
import shutil
import dte

# Directory where debit notes will be stored
NOTAS_DEBITO_DIR = os.path.join(os.path.dirname(__file__), "notas_debito")
# Directory where credit notes will be stored
NOTAS_CREDITO_DIR = os.path.join(os.path.dirname(__file__), "notas_credito")
# Directory where remision notes will be stored
NOTAS_REMISION_DIR = os.path.join(os.path.dirname(__file__), "notas_remision")
import json
from datetime import datetime, date, timedelta

CF_DIR = os.path.join(os.path.dirname(__file__), "facturas_consumidor_final")
CREDITO_DIR = os.path.join(os.path.dirname(__file__), "facturas_credito_fiscal")
TICKETS_DIR = os.path.join(os.path.dirname(__file__), "tickets")
# Additional locations where invoices may be stored
ADDITIONAL_DIRS = [
    os.path.join(os.path.dirname(__file__), "facturas", "consumidor_final"),
    os.path.join(os.path.dirname(__file__), "facturas", "credito_fiscal"),
]

# Pattern for file names generated by the system
DOC_PATTERN = re.compile(r"^\d{8}_.+_(ConsumidorFinal|CreditoFiscal|Ticket|NotaDebito|NotaCredito|NotaRemision)$")


class SendOptionsDialog(QDialog):
    """Simple dialog to choose where to send the invoice."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Enviar factura")
        layout = QVBoxLayout(self)
        self.email_cb = QCheckBox("Enviar por correo")
        self.hacienda_cb = QCheckBox("Enviar a Hacienda")
        layout.addWidget(self.email_cb)
        layout.addWidget(self.hacienda_cb)
        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)



class FacturacionTab(QWidget):
    """Tab para gestionar facturas y notas."""

    def __init__(self, manager, parent=None):
        super().__init__(parent)
        self.manager = manager
        self.email_thread = None
        self._setup_ui()
        self.load_invoices()

    def _setup_ui(self):
        main_layout = QHBoxLayout(self)

        left_layout = QVBoxLayout()

        filter_layout = QHBoxLayout()
        self.search_bar = QLineEdit()
        self.search_bar.setPlaceholderText("Buscar número o cliente")
        filter_layout.addWidget(self.search_bar)

        self.client_filter = QComboBox()
        self.client_filter.addItem("Todos", None)
        for c in self.manager._clientes:
            self.client_filter.addItem(c.get("nombre", ""), c.get("id"))
        filter_layout.addWidget(self.client_filter)

        self.vendedor_filter = QComboBox()
        self.vendedor_filter.addItem("Todos", None)
        for v in self.manager.db.get_trabajadores(solo_vendedores=True):
            self.vendedor_filter.addItem(v.get("nombre", ""), v.get("id"))
        filter_layout.addWidget(self.vendedor_filter)

        self.tipo_filter = QComboBox()
        self.tipo_filter.addItems(["Todos", "Consumidor final", "Crédito fiscal", "Ticket"])
        filter_layout.addWidget(self.tipo_filter)

        self.date_filter_cb = QCheckBox("Filtrar por fecha")
        self.quick_range = QComboBox()
        self.quick_range.addItems(["Personalizado", "Esta semana", "Este mes", "Este año"])
        self.date_from = QDateEdit(QDate.currentDate().addYears(-2))
        self.date_from.setCalendarPopup(True)
        self.date_to = QDateEdit(QDate.currentDate())
        self.date_to.setCalendarPopup(True)
        self.quick_range.setEnabled(False)
        self.date_from.setEnabled(False)
        self.date_to.setEnabled(False)
        for w in [self.date_filter_cb, self.quick_range, QLabel("Desde"), self.date_from,
                  QLabel("Hasta"), self.date_to]:
            filter_layout.addWidget(w)
        self.date_filter_cb.toggled.connect(self._toggle_date_filter)
        self.quick_range.currentIndexChanged.connect(self._apply_quick_range)
        self.update_btn = QPushButton("Actualizar")
        filter_layout.addWidget(self.update_btn)
        filter_layout.addStretch(1)
        left_layout.addLayout(filter_layout)

        self.table = QTableWidget(0, 5)
        self.table.setHorizontalHeaderLabels(["ID", "Fecha", "Cliente", "Total", "Estado"])
        self.table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        left_layout.addWidget(self.table)

        btns = QHBoxLayout()
        self.btn_ticket = QPushButton("Generar ticket virtual")
        self.btn_credito = QPushButton("Nota de crédito")
        self.btn_debito = QPushButton("Nota de débito")
        self.btn_estado = QPushButton("Estado")
        self.btn_enviar = QPushButton("Enviar")
        self.btn_enviar.setEnabled(False)
        self.btn_enviar_jws = QPushButton("Enviar JWS...")
        self.btn_eliminar = QPushButton("Eliminar")
        self.btn_eliminar.setStyleSheet(
            "background-color: #b71c1c; color: #fff; border-radius: 6px;"
        )
        btns.addWidget(self.btn_ticket)
        btns.addWidget(self.btn_credito)
        btns.addWidget(self.btn_debito)
        btns.addWidget(self.btn_estado)
        btns.addWidget(self.btn_enviar)
        btns.addWidget(self.btn_enviar_jws)
        btns.addWidget(self.btn_eliminar)
        btns.addStretch(1)
        left_layout.addLayout(btns)

        main_layout.addLayout(left_layout, 3)

        preview_layout = QVBoxLayout()
        self.preview_label = QLabel("Previsualización del PDF")
        self.preview_label.setAlignment(Qt.AlignCenter)
        self.preview_label.setStyleSheet("background:#DDD; padding:20px;")
        preview_layout.addWidget(self.preview_label)
        main_layout.addLayout(preview_layout, 2)

        # Connect signals
        self.update_btn.clicked.connect(self.refresh_and_reload)
        self.search_bar.textChanged.connect(self.load_invoices)
        self.client_filter.currentIndexChanged.connect(self.load_invoices)
        self.vendedor_filter.currentIndexChanged.connect(self.load_invoices)
        self.tipo_filter.currentIndexChanged.connect(self.load_invoices)
        self.date_from.dateChanged.connect(self.load_invoices)
        self.date_to.dateChanged.connect(self.load_invoices)
        self.table.itemSelectionChanged.connect(self.show_invoice)
        self.table.itemSelectionChanged.connect(self._update_send_btn)
        
        self.btn_ticket.clicked.connect(self.create_ticket)
        self.btn_credito.clicked.connect(lambda: self.create_nota("credito"))
        self.btn_debito.clicked.connect(lambda: self.create_nota("debito"))
        self.btn_estado.clicked.connect(self.change_estado)
        self.btn_enviar.clicked.connect(self.send_selected_invoice)
        self.btn_enviar_jws.clicked.connect(self.send_jws)
        self.btn_eliminar.clicked.connect(self.delete_files)

    def _toggle_date_filter(self, checked):
        self.quick_range.setEnabled(checked)
        custom = self.quick_range.currentIndex() == 0
        self.date_from.setEnabled(checked and custom)
        self.date_to.setEnabled(checked and custom)
        if checked:
            self._apply_quick_range()
        else:
            self.load_invoices()

    def _apply_quick_range(self):
        if not self.date_filter_cb.isChecked():
            return
        option = self.quick_range.currentText()
        today = date.today()
        if option == "Esta semana":
            start = today - timedelta(days=today.weekday())
            end = start + timedelta(days=6)
            self.date_from.setDate(QDate(start))
            self.date_to.setDate(QDate(end))
            self.date_from.setEnabled(False)
            self.date_to.setEnabled(False)
        elif option == "Este mes":
            start = today.replace(day=1)
            if today.month == 12:
                end = date(today.year, 12, 31)
            else:
                end = date(today.year, today.month + 1, 1) - timedelta(days=1)
            self.date_from.setDate(QDate(start))
            self.date_to.setDate(QDate(end))
            self.date_from.setEnabled(False)
            self.date_to.setEnabled(False)
        elif option == "Este año":
            start = date(today.year, 1, 1)
            end = date(today.year, 12, 31)
            self.date_from.setDate(QDate(start))
            self.date_to.setDate(QDate(end))
            self.date_from.setEnabled(False)
            self.date_to.setEnabled(False)
        else:
            self.date_from.setEnabled(True)
            self.date_to.setEnabled(True)
        self.load_invoices()

    def refresh_filters(self):
        """Update client and vendor filter combos with latest data."""
        self.client_filter.blockSignals(True)
        self.vendedor_filter.blockSignals(True)

        current_client = self.client_filter.currentData()
        current_vend = self.vendedor_filter.currentData()

        self.client_filter.clear()
        self.client_filter.addItem("Todos", None)
        for c in self.manager._clientes:
            self.client_filter.addItem(c.get("nombre", ""), c.get("id"))

        self.vendedor_filter.clear()
        self.vendedor_filter.addItem("Todos", None)
        for v in self.manager.db.get_trabajadores(solo_vendedores=True):
            self.vendedor_filter.addItem(v.get("nombre", ""), v.get("id"))

        def _restore(combo, value):
            if value is None:
                combo.setCurrentIndex(0)
                return
            for i in range(combo.count()):
                if combo.itemData(i) == value:
                    combo.setCurrentIndex(i)
                    return
            combo.setCurrentIndex(0)

        _restore(self.client_filter, current_client)
        _restore(self.vendedor_filter, current_vend)

        self.client_filter.blockSignals(False)
        self.vendedor_filter.blockSignals(False)

    def refresh_and_reload(self):
        """Refresh manager data and reload invoices."""
        self.manager.refresh_data()
        self.refresh_filters()
        self.load_invoices()

    def load_invoices(self):
        clientes = {c["id"]: c["nombre"] for c in self.manager._clientes}
        search = self.search_bar.text().lower() if hasattr(self, "search_bar") else ""
        if self.date_filter_cb.isChecked():
            d_from = self.date_from.date().toPyDate()
            d_to = self.date_to.date().toPyDate()
        else:
            d_from = d_to = None
        cli_id = self.client_filter.currentData()
        vend_id = self.vendedor_filter.currentData()
        tipo = self.tipo_filter.currentText()

        rows = self._get_invoices_from_db()
        rows.extend(self._get_tickets_from_db())
        for r in list(rows):
            fdate = r.get("_parsed_fecha")
            if self.date_filter_cb.isChecked():
                if d_from and fdate and fdate < d_from:
                    rows.remove(r)
                    continue
                if d_to and fdate and fdate > d_to:
                    rows.remove(r)
                    continue
            if cli_id and r.get("cliente_id") != cli_id:
                rows.remove(r)
                continue
            if vend_id and r.get("vendedor_id") != vend_id:
                rows.remove(r)
                continue
            cliente = clientes.get(r.get("cliente_id"), "")
            if search and search not in str(r.get("id", "")).lower() and search not in cliente.lower():
                rows.remove(r)

        rows.extend(self._find_orphan_documents())

        # Sort invoices, placing sales and tickets first, orphan documents at
        # the end, and ordering by date descending with undated entries last
        rows.sort(
            key=lambda r: (
                r.get("row_type") == "orphan",
                r.get("_parsed_fecha") is None,
                -(r.get("_parsed_fecha").toordinal() if r.get("_parsed_fecha") else 0),
            )
        )

        self.table.setRowCount(len(rows))
        for row, v in enumerate(rows):
            if v.get("row_type") in ("venta", "ticket"):
                self.table.setItem(row, 0, QTableWidgetItem(str(v.get("id"))))
                self.table.setItem(row, 1, QTableWidgetItem(v.get("fecha", "")))
                self.table.setItem(row, 2, QTableWidgetItem(clientes.get(v.get("cliente_id"), "")))
                total = v.get('total') or 0
                self.table.setItem(row, 3, QTableWidgetItem(f"${total:.2f}"))
                self.table.setItem(row, 4, QTableWidgetItem(v.get("estado", "")))
            else:
                self.table.setItem(row, 0, QTableWidgetItem(v.get("name", "")))
                self.table.setItem(row, 1, QTableWidgetItem(v.get("fecha", "")))
                self.table.setItem(row, 2, QTableWidgetItem(""))
                self.table.setItem(row, 3, QTableWidgetItem(""))
                self.table.setItem(row, 4, QTableWidgetItem(v.get("estado", "")))
            for col in range(5):
                item = self.table.item(row, col)
                if item:
                    item.setData(Qt.UserRole, v)
        if rows:
            self.table.selectRow(0)
        self._update_send_btn()

    def _find_orphan_documents(self):
        db_pdfs = set(r["ruta"] for r in self.manager.db.cursor.execute("SELECT ruta FROM facturas_pdf"))
        db_pdfs.update(r["ruta"] for r in self.manager.db.cursor.execute("SELECT ruta FROM tickets_pdf"))
        db_bases = {os.path.splitext(os.path.basename(p))[0] for p in db_pdfs}
        result = []
        folders = [CF_DIR, CREDITO_DIR, TICKETS_DIR] + ADDITIONAL_DIRS
        files = {}
        for folder in folders:
            if not os.path.isdir(folder):
                continue
            for root, _dirs, fnames in os.walk(folder):
                for fname in fnames:
                    base, ext = os.path.splitext(fname)
                    if ext.lower() not in ('.pdf', '.json'):
                        continue
                    if not DOC_PATTERN.match(base):
                        continue
                    entry = files.setdefault(base, {})
                    # prefer existing paths to keep deterministic order
                    entry.setdefault(ext.lower(), os.path.join(root, fname))

        for base, paths in files.items():
            pdf = paths.get('.pdf')
            js = paths.get('.json')
            if pdf and pdf in db_pdfs:
                continue
            if base in db_bases:
                continue
            mtime = None
            if pdf and os.path.exists(pdf):
                mtime = os.path.getmtime(pdf)
            elif js and os.path.exists(js):
                mtime = os.path.getmtime(js)
            fecha = datetime.fromtimestamp(mtime).strftime('%Y-%m-%d') if mtime else ''
            estado = 'Sin venta'
            if not pdf or not js:
                estado = 'Incompleta'
            else:
                try:
                    with open(js, 'r', encoding='utf-8') as fh:
                        json.load(fh)
                except Exception:
                    estado = 'Incompleta'
            result.append({
                'row_type': 'orphan',
                'name': base,
                'pdf': pdf,
                'json': js,
                'fecha': fecha,
                '_parsed_fecha': datetime.fromtimestamp(mtime).date() if mtime else None,
                'estado': estado,
            })
        return result

    def _get_invoices_from_db(self):
        ventas = {v["id"]: v for v in self.manager.db.get_ventas()}
        clientes = {c["id"]: c.get("nombre", "") for c in self.manager._clientes}
        result = []
        for row in self.manager.db.cursor.execute("SELECT venta_id, ruta FROM facturas_pdf"):
            venta_id = row["venta_id"]
            venta = ventas.get(venta_id)
            pdf = row["ruta"]
            js = os.path.splitext(pdf)[0] + ".json"

            # Remove stale DB records if both files are missing
            if not os.path.exists(pdf) and not os.path.exists(js):
                self.manager.db.delete_factura_pdf(venta_id)
                continue

            estado = venta.get("estado", "") if venta else "Sin venta"
            if not os.path.exists(pdf) or not os.path.exists(js):
                estado = "Incompleta"
            else:
                try:
                    with open(js, 'r', encoding='utf-8') as fh:
                        json.load(fh)
                except Exception:
                    estado = "Incompleta"
            fecha = venta.get("fecha", "") if venta else ''
            try:
                fdate = datetime.strptime(fecha.split()[0], "%Y-%m-%d").date() if fecha else None
            except Exception:
                fdate = None
            result.append({
                'row_type': 'venta',
                'id': row['venta_id'],
                'pdf': pdf,
                'json': js if os.path.exists(js) else None,
                'fecha': fecha,
                '_parsed_fecha': fdate,
                'cliente_id': venta.get('cliente_id') if venta else None,
                'vendedor_id': venta.get('vendedor_id') if venta else None,
                'total': venta.get('total') if venta else None,
                'estado': estado,
            })
        return result

    def _get_tickets_from_db(self):
        ventas = {v["id"]: v for v in self.manager.db.get_ventas()}
        clientes = {c["id"]: c.get("nombre", "") for c in self.manager._clientes}
        result = []
        for row in self.manager.db.cursor.execute("SELECT venta_id, ruta FROM tickets_pdf"):
            venta_id = row["venta_id"]
            venta = ventas.get(venta_id)
            pdf = row["ruta"]
            js = os.path.splitext(pdf)[0] + ".json"

            if not os.path.exists(pdf) and not os.path.exists(js):
                self.manager.db.delete_ticket_pdf(venta_id)
                continue

            estado = venta.get("estado", "") if venta else "Sin venta"
            if not os.path.exists(pdf) or not os.path.exists(js):
                estado = "Incompleta"
            else:
                try:
                    with open(js, "r", encoding="utf-8") as fh:
                        json.load(fh)
                except Exception:
                    estado = "Incompleta"
            fecha = venta.get("fecha", "") if venta else ""
            try:
                fdate = datetime.strptime(fecha.split()[0], "%Y-%m-%d").date() if fecha else None
            except Exception:
                fdate = None
            result.append({
                "row_type": "ticket",
                "id": row["venta_id"],
                "pdf": pdf,
                "json": js if os.path.exists(js) else None,
                "fecha": fecha,
                "_parsed_fecha": fdate,
                "cliente_id": venta.get("cliente_id") if venta else None,
                "vendedor_id": venta.get("vendedor_id") if venta else None,
                "total": venta.get("total") if venta else None,
                "estado": estado,
            })
        return result

    def _selected_entry(self):
        selected_rows = self.table.selectionModel().selectedRows()
        if not selected_rows:
            return None
        row = selected_rows[0].row()
        item = self.table.item(row, 0)
        return item.data(Qt.UserRole) if item else None

    def _selected_venta(self):
        data = self._selected_entry()
        if data and data.get("row_type") in ("venta", "ticket"):
            return data.get("id")
        return None

    def _update_send_btn(self):
        entry = self._selected_entry()
        enabled = False
        if entry:
            rtype = entry.get("row_type")
            if rtype in ("venta", "ticket"):
                enabled = True
            elif rtype == "orphan" and entry.get("json") and entry.get("estado") != "Incompleta":
                enabled = True
        self.btn_enviar.setEnabled(enabled)

    def _show_validation_errors(self, errors, json_path):
        """Display validation errors and allow opening a report."""
        msg = QMessageBox(self)
        msg.setWindowTitle("Enviar a Hacienda")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("El DTE contiene errores de validación:")
        msg.setInformativeText("\n".join(f"- {e}" for e in errors))
        open_btn = msg.addButton("Abrir reporte", QMessageBox.ActionRole)
        msg.addButton(QMessageBox.Close)
        msg.exec_()
        if msg.clickedButton() == open_btn and json_path:
            report_path = os.path.splitext(json_path)[0] + ".md"
            with open(report_path, "w", encoding="utf-8") as fh:
                fh.write("# Errores de validación\n\n")
                for e in errors:
                    fh.write(f"- {e}\n")
            QDesktopServices.openUrl(QUrl.fromLocalFile(report_path))

    def send_selected_invoice(self):
        venta_id = self._selected_venta()
        entry = self._selected_entry()
        if not entry:
            QMessageBox.warning(self, "Enviar", "Seleccione un documento")
            return

        dialog = SendOptionsDialog(self)
        dialog.email_cb.setChecked(True)
        if dialog.exec_() != QDialog.Accepted:
            return

        if dialog.email_cb.isChecked():
            if entry.get("row_type") == "venta":
                self._send_invoice_email(venta_id)
            elif entry.get("row_type") == "ticket":
                self._send_ticket_email(venta_id)
            elif entry.get("row_type") == "orphan":
                self._send_orphan_email(entry)
        if dialog.hacienda_cb.isChecked():
            if entry.get("row_type") == "orphan":
                json_path = entry.get("json")
                try:
                    resp = dte.transmitir_dte_orphan(self.manager.db, json_path)
                    if resp.get("estado") == "Error":
                        QMessageBox.critical(
                            self, "Enviar a Hacienda", resp.get("detalle", "Error")
                        )
                    else:
                        QMessageBox.information(
                            self, "Enviar a Hacienda", "Documento enviado"
                        )
                except dte.DTEValidationError as exc:
                    self._show_validation_errors(exc.errors, exc.json_path)
                except Exception as exc:
                    QMessageBox.critical(
                        self, "Enviar a Hacienda", str(exc)
                    )
            else:
                tipo = "03" if entry.get("row_type") == "ticket" else "01"
                try:
                    resp = transmitir_dte(self.manager.db, venta_id, tipo_dte=tipo)
                    if resp.get("estado") == "Error":
                        QMessageBox.critical(
                            self, "Enviar a Hacienda", resp.get("detalle", "Error")
                        )
                    else:
                        QMessageBox.information(
                            self, "Enviar a Hacienda", "Documento enviado"
                        )
                except dte.DTEValidationError as exc:
                    self._show_validation_errors(exc.errors, exc.json_path)
                except Exception as exc:
                    QMessageBox.critical(
                        self, "Enviar a Hacienda", str(exc)
                    )

    def send_jws(self):
        fname, _ = QFileDialog.getOpenFileName(
            self,
            "Seleccionar JWS",
            "",
            "JWS (*.jws *.json)",
            options=QFileDialog.DontUseNativeDialog,
        )
        if not fname:
            return
        try:
            with open(fname, "r", encoding="utf-8") as fh:
                content = fh.read()
        except Exception as exc:
            QMessageBox.critical(self, "Enviar a Hacienda", f"Error al leer archivo: {exc}")
            return

        is_json = True
        try:
            json.loads(content)
        except Exception:
            is_json = False

        try:
            if is_json:
                resp = dte.transmitir_dte_orphan(self.manager.db, fname)
            else:
                resp = dte.enviar_dte_a_hacienda(content)

            if resp.get("estado") in ("Error", "Rechazado"):
                QMessageBox.critical(
                    self, "Enviar a Hacienda", resp.get("detalle") or resp.get("errores", "Error")
                )
            else:
                QMessageBox.information(
                    self, "Enviar a Hacienda", "Documento enviado"
                )
        except dte.DTEValidationError as exc:
            self._show_validation_errors(exc.errors, exc.json_path)
        except Exception as exc:
            QMessageBox.critical(self, "Enviar a Hacienda", str(exc))

    def _send_invoice_email(self, venta_id):
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            QMessageBox.warning(self, "Enviar por correo", "No se encontró la venta seleccionada.")
            return

        cliente_email = ""
        if venta.get("cliente_id"):
            cli = next((c for c in self.manager._clientes if c["id"] == venta["cliente_id"]), None)
            if cli:
                cliente_email = cli.get("email", "")
        if not cliente_email:
            QMessageBox.warning(self, "Enviar por correo", "El cliente no tiene correo registrado.")
            return

        pdf_path = self.manager.db.get_factura_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            pdf_path = self._generate_invoice_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            QMessageBox.warning(self, "Enviar por correo", "No se pudo generar el PDF.")
            return
        json_path = os.path.splitext(pdf_path)[0] + ".json"
        if not os.path.exists(json_path):
            pdf_path = self._generate_invoice_pdf(venta_id)
            json_path = os.path.splitext(pdf_path)[0] + ".json"
            if not os.path.exists(json_path):
                QMessageBox.warning(self, "Enviar por correo", "No se encontró el JSON firmado.")
                return

        creds = {}
        if os.path.exists(DATOS_NEGOCIO_PATH):
            try:
                with open(DATOS_NEGOCIO_PATH, "r", encoding="utf-8") as f:
                    creds = json.load(f)
            except Exception:
                creds = {}
        server = creds.get("smtp_server")
        port = creds.get("smtp_port")
        user = creds.get("email_usuario")
        password = os.getenv("INVENTARIO_EMAIL_PASSWORD") or creds.get("email_contrasena")
        if not all([server, port, user, password]):
            QMessageBox.warning(self, "Enviar por correo", "Credenciales SMTP incompletas.")
            return

        subject = "Factura"
        body = (
            "Adjunto se envía la representación gráfica en PDF y el documento firmado en formato JSON"
        )

        self.btn_enviar.setEnabled(False)
        self.email_thread = EmailSender(
            server,
            port,
            user,
            password,
            cliente_email,
            subject,
            body,
            [pdf_path, json_path],
        )
        self.email_thread.finished.connect(self._on_email_sent)
        self.email_thread.start()

    def _send_orphan_email(self, entry):
        json_path = entry.get("json")
        pdf_path = entry.get("pdf")
        dest, ok = QInputDialog.getText(
            self, "Enviar por correo", "Correo del destinatario:")
        if not ok or not dest:
            return
        if not json_path or not os.path.exists(json_path):
            QMessageBox.warning(self, "Enviar por correo", "No se encontró el JSON.")
            return
        attachments = [json_path]
        if pdf_path and os.path.exists(pdf_path):
            attachments.insert(0, pdf_path)
        else:
            QMessageBox.warning(
                self, "Enviar por correo", "No se encontró PDF. Solo se adjuntará el JSON."
            )
        creds = {}
        if os.path.exists(DATOS_NEGOCIO_PATH):
            try:
                with open(DATOS_NEGOCIO_PATH, "r", encoding="utf-8") as f:
                    creds = json.load(f)
            except Exception:
                creds = {}
        server = creds.get("smtp_server")
        port = creds.get("smtp_port")
        user = creds.get("email_usuario")
        password = os.getenv("INVENTARIO_EMAIL_PASSWORD") or creds.get("email_contrasena")
        if not all([server, port, user, password]):
            QMessageBox.warning(self, "Enviar por correo", "Credenciales SMTP incompletas.")
            return
        subject = "Factura"
        body = (
            "Adjunto se envía la representación gráfica en PDF y el documento firmado en formato JSON"
        )
        self.btn_enviar.setEnabled(False)
        self.email_thread = EmailSender(
            server,
            port,
            user,
            password,
            dest,
            subject,
            body,
            attachments,
        )
        self.email_thread.finished.connect(self._on_email_sent)
        self.email_thread.start()

    def _on_email_sent(self, success, message):
        self.btn_enviar.setEnabled(True)
        if success:
            QMessageBox.information(self, "Enviar por correo", message)
        else:
            QMessageBox.critical(self, "Enviar por correo", message)
        self.email_thread = None

    def create_ticket(self):
        venta_id = self._selected_venta()
        if venta_id is None:
            raise ValueError("No sale selected")
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        detalles = self.manager.db.get_detalles_venta(venta_id)
        extra = {}
        raw_extra = venta.get("extra") if venta else None
        if raw_extra:
            try:
                extra = json.loads(raw_extra)
            except Exception:
                extra = {}
        fname, _ = QFileDialog.getSaveFileName(
            self,
            "Guardar ticket",
            "ticket.pdf",
            "PDF (*.pdf)",
            options=QFileDialog.DontUseNativeDialog,
        )
        if not fname:
            return
        generar_ticket_personalizado(venta, detalles, fname, dte_data=extra)
        QMessageBox.information(self, "Ticket", "Ticket generado correctamente")

    def create_nota(self, tipo):
        venta_id = self._selected_venta()
        if venta_id is None:
            QMessageBox.warning(self, "Nota", "Seleccione una venta")
            return
        monto, ok = QInputDialog.getDouble(self, "Monto", "Monto de la nota", 0, decimals=2)
        if not ok:
            return
        motivo, ok2 = QInputDialog.getText(self, "Motivo", "Motivo")
        if not ok2:
            return
        fecha = QDate.currentDate().toString("yyyy-MM-dd")
        nota_id = self.manager.db.add_nota(venta_id, tipo, fecha, monto, motivo)

        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        detalles = self.manager.db.get_detalles_venta(venta_id)
        credito_info = self.manager.db.get_venta_credito_fiscal(venta_id)
        venta_data = dict(venta)
        if credito_info:
            venta_data.update(credito_info)

        if venta_data.get("vendedor_id"):
            trabajador = self.manager.db.get_trabajador(venta_data["vendedor_id"])
            if trabajador:
                venta_data["vendedor_nombre"] = trabajador.get("nombre", "")

        sumas = descuentos = 0
        ventas_exentas = ventas_no_sujetas = iva = 0
        for d in detalles:
            base_total = d.get("precio_unitario", 0) * d.get("cantidad", 0)
            desc = d.get("descuento", 0)
            if d.get("descuento_tipo") == "%":
                desc = base_total * d.get("descuento", 0) / 100
            base = base_total - desc
            iva_item = d.get("iva", 0)
            tipo_fiscal = d.get("tipo_fiscal", "").lower()
            if tipo_fiscal == "venta exenta":
                d["ventas_exentas"] = base
                ventas_exentas += base
            elif tipo_fiscal == "venta no sujeta":
                d["ventas_no_sujetas"] = base
                ventas_no_sujetas += base
            else:
                d["ventas_gravadas"] = base
                sumas += base_total
                descuentos += desc
                iva += iva_item

        subtotal = (sumas - descuentos) + iva
        total = subtotal + ventas_exentas + ventas_no_sujetas
        venta_data.update(
            {
                "sumas": sumas,
                "descuentos": descuentos,
                "iva": iva,
                "ventas_exentas": ventas_exentas,
                "ventas_no_sujetas": ventas_no_sujetas,
                "subtotal": subtotal,
                "total": total,
            }
        )
        if not venta_data.get("total_letras"):
            try:
                venta_data["total_letras"] = monto_a_texto_sv(total)
            except Exception:
                venta_data["total_letras"] = ""

        cliente = None
        if venta.get("cliente_id"):
            cliente = next((c for c in self.manager._clientes if c["id"] == venta["cliente_id"]), None)
        distribuidor = None
        if venta.get("Distribuidor_id"):
            distribuidor = next(
                (d for d in self.manager._Distribuidores if d["id"] == venta["Distribuidor_id"]),
                None,
            )

        conf = {
            "debito": (NOTAS_DEBITO_DIR, "NotaDebito", generar_nota_debito_pdf, generar_nota_debito_json),
            "credito": (NOTAS_CREDITO_DIR, "NotaCredito", generar_nota_credito_pdf, generar_nota_credito_json),
            "remision": (NOTAS_REMISION_DIR, "NotaRemision", generar_nota_remision_pdf, generar_nota_remision_json),
        }
        out_dir, doc_type, pdf_func, json_func = conf.get(tipo)
        os.makedirs(out_dir, exist_ok=True)
        pdf_path, json_path = get_document_paths(
            venta.get("fecha"), cliente.get("nombre") if cliente else "", nota_id, doc_type
        )
        pdf_func(
            venta_data,
            detalles,
            cliente or {},
            distribuidor or {},
            archivo=pdf_path,
        )
        nota_json = json_func(self.manager.db, nota_id)
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump(nota_json, fh, ensure_ascii=False, indent=2)

        QMessageBox.information(self, "Nota", "Nota registrada")
        self.load_invoices()

    def change_estado(self):
        venta_id = self._selected_venta()
        if venta_id is None:
            QMessageBox.warning(self, "Estado", "Seleccione una venta")
            return
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            QMessageBox.warning(self, "Estado", "No se encontró la venta seleccionada")
            return
        from dialogs import EstadoVentaDialog
        dialog = EstadoVentaDialog(venta.get("estado", "Pagada"), self)
        if dialog.exec_():
            estado = dialog.get_estado()
            self.manager.db.update_venta_estado(venta_id, estado)
            self.load_invoices()
            parent = self.parent()
            if parent and hasattr(parent, "sales_tab"):
                parent.sales_tab.load_sales()

    def delete_files(self):
        """Elimina PDF y JSON asociados a la venta seleccionada."""
        data = self._selected_entry()
        if not data:
            QMessageBox.warning(self, "Eliminar", "Seleccione una venta")
            return
        paths = []
        pdf_path = None
        ticket_path = None
        row_type = data.get("row_type")
        if row_type in ("venta", "ticket"):
            venta_id = data.get("id")
            if row_type == "venta":
                pdf_path = self.manager.db.get_factura_pdf(venta_id)
                if pdf_path:
                    paths.append(pdf_path)
                    paths.append(os.path.splitext(pdf_path)[0] + ".json")
                ticket_path = self.manager.db.get_ticket_pdf(venta_id)
                if ticket_path:
                    paths.append(ticket_path)
                    paths.append(os.path.splitext(ticket_path)[0] + ".json")
            else:
                ticket_path = data.get("pdf")
                if ticket_path:
                    paths.append(ticket_path)
                    json_path = data.get("json") or os.path.splitext(ticket_path)[0] + ".json"
                    paths.append(json_path)
        else:
            for p in [data.get("pdf"), data.get("json")]:
                if p:
                    paths.append(p)
        paths = [p for p in paths if os.path.exists(p)]
        if not paths:
            if row_type in ("venta", "ticket"):
                confirm = QMessageBox.question(
                    self,
                    "Eliminar",
                    "No se encontraron archivos. ¿Eliminar registros?",
                    QMessageBox.Yes | QMessageBox.No,
                )
                if confirm == QMessageBox.Yes:
                    if row_type == "venta" and pdf_path:
                        self.manager.db.delete_factura_pdf(venta_id)
                    if ticket_path:
                        self.manager.db.delete_ticket_pdf(venta_id)
                    QMessageBox.information(self, "Eliminar", "Registros eliminados")
                    self.load_invoices()
                else:
                    QMessageBox.information(self, "Eliminar", "No se eliminaron registros")
            else:
                QMessageBox.information(self, "Eliminar", "No se encontraron archivos")
            return
        confirm = QMessageBox.question(
            self,
            "Eliminar",
            "¿Eliminar archivos?",
            QMessageBox.Yes | QMessageBox.No,
        )
        if confirm != QMessageBox.Yes:
            return
        for p in paths:
            try:
                os.remove(p)
            except OSError:
                pass
        if row_type == "venta":
            if pdf_path:
                self.manager.db.delete_factura_pdf(venta_id)
            if ticket_path:
                self.manager.db.delete_ticket_pdf(venta_id)
        elif row_type == "ticket":
            if ticket_path:
                self.manager.db.delete_ticket_pdf(venta_id)
        QMessageBox.information(self, "Eliminar", "Archivos eliminados")
        self.load_invoices()

    # ------------------------------------------------------------------
    # Previsualización de facturas
    # ------------------------------------------------------------------
    def show_invoice(self):
        if self.table.currentRow() < 0:
            self.preview_label.setText("Previsualización del PDF")
            self._clear_preview_files()
            return
        data = self._selected_entry()
        if not data:
            self.preview_label.setText("Previsualización del PDF")
            self._clear_preview_files()
            return
        if data.get("row_type") == "venta":
            self._update_preview(data.get("id"))
        else:
            pdf = data.get("pdf")
            if pdf and os.path.exists(pdf):
                self._show_pdf_preview(pdf)
            else:
                self.preview_label.setText("No hay PDF")
                self._clear_preview_files()

    def _clear_preview_files(self):
        """Remove temporary preview image without deleting stored PDFs."""
        img = getattr(self, "preview_image_file", None)
        if img and os.path.exists(img):
            try:
                os.remove(img)
            except OSError:
                pass
        self.preview_pdf_file = None
        self.preview_image_file = None

    def _show_pdf_preview(self, pdf_path):
        self._clear_preview_files()
        prefix = tempfile.mktemp()
        try:
            png_path = prefix + ".png"
            if shutil.which("pdftoppm"):
                subprocess.run([
                    "pdftoppm",
                    "-png",
                    "-singlefile",
                    pdf_path,
                    prefix,
                ], check=True)
            else:
                import fitz

                doc = fitz.open(pdf_path)
                page = doc.load_page(0)
                pix = page.get_pixmap()
                pix.save(png_path)

            self.preview_pdf_file = pdf_path
            self.preview_image_file = png_path
            pixmap = QPixmap(png_path)
            if pixmap.isNull():
                raise RuntimeError("failed to load image")
            scaled = pixmap.scaled(
                int(self.preview_label.width() * 0.9),
                int(self.preview_label.height() * 0.9),
                Qt.KeepAspectRatio,
                Qt.SmoothTransformation,
            )
            self.preview_label.setPixmap(scaled)
            self.preview_label.setText("")
        except Exception:
            self.preview_label.setText("No se pudo generar previsualización")
            self._clear_preview_files()

    def _update_preview(self, venta_id):
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            self.preview_label.setText("Previsualización del PDF")
            return

        self._clear_preview_files()

        is_ticket = not venta.get("cliente_id") and not self.manager.db.get_venta_credito_fiscal(venta_id)
        if is_ticket:
            pdf_path = self.manager.db.get_ticket_pdf(venta_id)
            if not pdf_path or not os.path.exists(pdf_path):
                pdf_path = self._generate_ticket_pdf(venta_id)
        else:
            pdf_path = self.manager.db.get_factura_pdf(venta_id)
            if not pdf_path or not os.path.exists(pdf_path):
                pdf_path = self._generate_invoice_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            self.preview_label.setText("No se pudo generar previsualización")
            return

        self._show_pdf_preview(pdf_path)

    def _generate_invoice_pdf(self, venta_id):
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            return None

        credito_info = self.manager.db.get_venta_credito_fiscal(venta_id)
        detalles = self.manager.db.get_detalles_venta(venta_id)

        venta_data = dict(venta)
        if credito_info:
            venta_data.update(credito_info)

        if venta_data.get("vendedor_id"):
            trabajador = self.manager.db.get_trabajador(venta_data["vendedor_id"])
            if trabajador:
                venta_data["vendedor_nombre"] = trabajador.get("nombre", "")

        sumas = descuentos = 0
        ventas_exentas = ventas_no_sujetas = iva = 0
        for d in detalles:
            base_total = d.get("precio_unitario", 0) * d.get("cantidad", 0)
            desc = d.get("descuento", 0)
            if d.get("descuento_tipo") == "%":
                desc = base_total * d.get("descuento", 0) / 100
            base = base_total - desc
            iva_item = d.get("iva", 0)
            tipo = d.get("tipo_fiscal", "").lower()
            if tipo == "venta exenta":
                d["ventas_exentas"] = base
                ventas_exentas += base
            elif tipo == "venta no sujeta":
                d["ventas_no_sujetas"] = base
                ventas_no_sujetas += base
            else:
                d["ventas_gravadas"] = base
                sumas += base_total
                descuentos += desc
                iva += iva_item

        subtotal = (sumas - descuentos) + iva
        total = subtotal + ventas_exentas + ventas_no_sujetas
        venta_data.update(
            {
                "sumas": sumas,
                "descuentos": descuentos,
                "iva": iva,
                "ventas_exentas": ventas_exentas,
                "ventas_no_sujetas": ventas_no_sujetas,
                "subtotal": subtotal,
                "total": total,
            }
        )
        if not venta_data.get("total_letras"):
            try:
                venta_data["total_letras"] = monto_a_texto_sv(total)
            except Exception:
                venta_data["total_letras"] = ""

        cliente = None
        if venta.get("cliente_id"):
            cliente = next((c for c in self.manager._clientes if c["id"] == venta["cliente_id"]), None)
        distribuidor = None
        if venta.get("Distribuidor_id"):
            distribuidor = next(
                (d for d in self.manager._Distribuidores if d["id"] == venta["Distribuidor_id"]),
                None,
            )

        extra = venta_data.get("extra") or {}
        if isinstance(extra, str):
            try:
                extra = json.loads(extra)
            except Exception:
                extra = {}
        if not venta_data.get("venta_a_cuenta_de"):
            venta_data["venta_a_cuenta_de"] = extra.get("venta_a_cuenta_de", "")
        if not venta_data.get("documento_venta_a_cuenta"):
            venta_data["documento_venta_a_cuenta"] = extra.get("documento_venta_a_cuenta", "")
        dte_json = extra.get("dteJson") or extra.get("dte_json") or {}
        ident = dte_json.get("identificacion", {})
        codigo_generacion = venta_data.get("codigo_generacion") or ident.get("codigoGeneracion", "")
        numero_control = venta_data.get("numero_control") or dte_json.get("numeroControl", "")
        sello_recepcion = venta_data.get("sello_recepcion") or extra.get("selloRecibido", "")
        tipo_operacion = venta_data.get("tipo_operacion") or ident.get("tipoOperacion")
        if tipo_operacion is None:
            tipo_operacion = 1
        tipo_contingencia = venta_data.get("tipo_contingencia") or ident.get("tipoContingencia")
        fecha_generacion = venta_data.get("fecha_generacion") or ident.get("fecGeneracion", "")

        if tipo_operacion == 1 and not sello_recepcion:
            sello_recepcion = f"SELLO-{uuid.uuid4().hex[:8]}"
            venta_data["sello_recepcion"] = sello_recepcion
        venta_data["tipo_operacion"] = tipo_operacion
        tipo_modelo = 2 if tipo_operacion == 2 else 1
        
        tipo_doc = "Crédito Fiscal" if credito_info else "Consumidor Final"
        doc_key = "CreditoFiscal" if credito_info else "ConsumidorFinal"
        cliente_nombre = cliente.get("nombre") if cliente else ""
        file_path, json_path = get_document_paths(
            venta_data.get("fecha"), cliente_nombre, numero_control or venta_id, doc_key
        )

        generar_factura_electronica_pdf(
            venta_data,
            detalles,
            cliente or {},
            distribuidor or {},
            tipo_doc,
            archivo=file_path,
            codigo_generacion=codigo_generacion,
            numero_control=numero_control,
            sello_recepcion=sello_recepcion,
            tipo_modelo=tipo_modelo,
            tipo_operacion=tipo_operacion,
            fecha_generacion=fecha_generacion,
            tipo_contingencia=tipo_contingencia,
            ambiente=ident.get("ambiente", "00"),
        )
        json_data = build_invoice_json(venta_data, cliente or {}, detalles)
        with open(json_path, 'w', encoding='utf-8') as fh:
            json.dump(json_data, fh, ensure_ascii=False, indent=2)
        if tipo_operacion == 2:
            self.manager.db.add_dte_pendiente(venta_id, json_data, str(tipo_operacion))
        self.manager.db.add_factura_pdf(venta_id, tipo_doc, file_path)
        return file_path

    def _generate_ticket_pdf(self, venta_id):
        """Generate and store the ticket PDF for the given sale."""
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            return None

        detalles = self.manager.db.get_detalles_venta(venta_id)
        extra = {}
        raw_extra = venta.get("extra") if venta else None
        if raw_extra:
            try:
                extra = json.loads(raw_extra)
            except Exception:
                extra = {}

        cliente = None
        if venta.get("cliente_id"):
            cliente = next((c for c in self.manager._clientes if c["id"] == venta["cliente_id"]), None)
        cliente_nombre = cliente.get("nombre") if cliente else ""

        filename, json_path = get_document_paths(
            venta.get("fecha"), cliente_nombre, venta_id, "Ticket"
        )

        generar_ticket_personalizado(venta, detalles, filename, dte_data=extra)
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump({"venta": venta, "detalles": detalles}, fh, ensure_ascii=False, indent=2)
        self.manager.db.add_ticket_pdf(venta_id, filename)
        return filename

    def _send_ticket_email(self, venta_id):
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            QMessageBox.warning(self, "Enviar ticket", "No se encontró la venta seleccionada.")
            return

        cliente_email = ""
        if venta.get("cliente_id"):
            cli = next((c for c in self.manager._clientes if c["id"] == venta["cliente_id"]), None)
            if cli:
                cliente_email = cli.get("email", "")
        if not cliente_email:
            QMessageBox.warning(self, "Enviar ticket", "El cliente no tiene correo registrado.")
            return

        pdf_path = self.manager.db.get_ticket_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            pdf_path = self._generate_ticket_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            QMessageBox.warning(self, "Enviar ticket", "No se pudo generar el ticket.")
            return
        json_path = os.path.splitext(pdf_path)[0] + ".json"
        if not os.path.exists(json_path):
            pdf_path = self._generate_ticket_pdf(venta_id)
            json_path = os.path.splitext(pdf_path)[0] + ".json"
            if not os.path.exists(json_path):
                QMessageBox.warning(self, "Enviar ticket", "No se encontró el JSON firmado.")
                return

        creds = {}
        if os.path.exists(DATOS_NEGOCIO_PATH):
            try:
                with open(DATOS_NEGOCIO_PATH, "r", encoding="utf-8") as f:
                    creds = json.load(f)
            except Exception:
                creds = {}
        server = creds.get("smtp_server")
        port = creds.get("smtp_port")
        user = creds.get("email_usuario")
        password = os.getenv("INVENTARIO_EMAIL_PASSWORD") or creds.get("email_contrasena")
        if not all([server, port, user, password]):
            QMessageBox.warning(self, "Enviar ticket", "Credenciales SMTP incompletas.")
            return

        subject = "Ticket"
        body = (
            "Adjunto se envía la representación gráfica en PDF y el documento firmado en formato JSON"
        )

        self.btn_enviar.setEnabled(False)
        self.email_thread = EmailSender(
            server,
            port,
            user,
            password,
            cliente_email,
            subject,
            body,
            [pdf_path, json_path],
        )
        self.email_thread.finished.connect(self._on_email_sent)
        self.email_thread.start()

