from PyQt5.QtWidgets import (
    QWidget,
    QVBoxLayout,
    QHBoxLayout,
    QTableWidget,
    QTableWidgetItem,
    QPushButton,
    QFileDialog,
    QInputDialog,
    QMessageBox,
    QLineEdit,
    QDateEdit,
    QAbstractItemView,
    QHeaderView,
    QLabel,
    QComboBox,
    QDialog,
    QDialogButtonBox,
    QCheckBox,
    QRadioButton,
    QListWidget,
    QListWidgetItem,
    QPlainTextEdit,
)
from PyQt5.QtCore import QDate, Qt, QUrl, QTimer, QEvent
from PyQt5.QtGui import QPixmap, QDesktopServices
import os
import re

from ticket_pdf import generar_ticket_personalizado
from factura_sv import (
    generar_nota_credito_pdf,
    generar_nota_debito_pdf,
    generar_nota_remision_pdf,
)
from dte import (
    transmitir_dte,
    enviar_nota_credito,
    enviar_nota_debito,
    enviar_nota_remision,
)
from nota_debito_electronica import generar_nde_desde_dte
from nota_remision import generar_nota_remision_desde_db
import nota_credito_electronica
from utils.docs import get_document_paths, get_dte_document_paths
from utils.doc_generation import generate_invoice_pdf
from utils.email_sender import EmailSender
from utils.jws import sign_and_save
from utils.stable_json import save_file, stable_stringify
from utils.sanitize import limpiar_doc, solo_digitos
from utils import catalogos
from paths import DATOS_NEGOCIO_PATH
import tempfile
import subprocess
import shutil
import dte
from dialogs.nota_detalle_dialog import NotaDetalleDialog
from dialogs.invoice_detail_dialog import InvoiceDetailDialog
from decimal import Decimal

# Directory where debit notes will be stored
NOTAS_DEBITO_DIR = os.path.join(os.path.dirname(__file__), "notas_debito")
# Directory where credit notes will be stored
NOTAS_CREDITO_DIR = os.path.join(os.path.dirname(__file__), "notas_credito")
# Directory where remision notes will be stored
NOTAS_REMISION_DIR = os.path.join(os.path.dirname(__file__), "notas_remision")
import json
from datetime import datetime, date, timedelta

CF_DIR = os.path.join(os.path.dirname(__file__), "facturas_consumidor_final")
CREDITO_DIR = os.path.join(os.path.dirname(__file__), "facturas_credito_fiscal")
TICKETS_DIR = os.path.join(os.path.dirname(__file__), "tickets")
# Additional locations where invoices may be stored
ADDITIONAL_DIRS = [
    os.path.join(os.path.dirname(__file__), "facturas", "consumidor_final"),
    os.path.join(os.path.dirname(__file__), "facturas", "credito_fiscal"),
]

# Pattern for file names generated by the system
DOC_PATTERN = re.compile(r"^\d{8}_.+_(ConsumidorFinal|CreditoFiscal|Ticket|NotaDebito|NotaCredito|NotaRemision)$")

# Mapping of ``identificacion.tipoDte`` codes to human readable descriptions
TIPO_DTE_DESC = {
    "01": "Consumidor final",
    "03": "Crédito fiscal",
    "04": "Nota de remisión",
    "05": "Nota de crédito",
    "06": "Nota de débito",
}


class SendOptionsDialog(QDialog):
    """Simple dialog to choose where to send the invoice."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Enviar factura")
        layout = QVBoxLayout(self)
        self.email_cb = QCheckBox("Enviar por correo")
        self.hacienda_cb = QCheckBox("Enviar a Hacienda")
        layout.addWidget(self.email_cb)
        layout.addWidget(self.hacienda_cb)
        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)



class NotaRemisionExtWidget(QWidget):
    """Widget reutilizable para capturar datos de entrega de la NR."""

    def __init__(self, db, parent=None):
        super().__init__(parent)
        self.db = db
        self.cli_data = None
        self._build_ui()

    def _build_ui(self):
        layout = QVBoxLayout(self)

        # Persona que entrega
        layout.addWidget(QLabel("Persona que entrega"))
        self.emp_search = QLineEdit()
        self.emp_search.setPlaceholderText("Buscar empleado por nombre, DUI o NIT…")
        layout.addWidget(self.emp_search)
        self.emp_results = QListWidget()
        self.emp_results.addItem("Escribe para buscar…")
        self.emp_results.item(0).setFlags(Qt.NoItemFlags)
        layout.addWidget(self.emp_results)

        self.nomb_entrega = QLineEdit()
        self.docu_entrega = QLineEdit()
        for label, widget in [
            ("Nombre entrega:", self.nomb_entrega),
            ("Documento entrega:", self.docu_entrega),
        ]:
            row = QHBoxLayout()
            row.addWidget(QLabel(label))
            row.addWidget(widget)
            layout.addLayout(row)

        # Persona que recibe
        layout.addWidget(QLabel("Persona que recibe"))
        self.cli_search = QLineEdit()
        self.cli_search.setPlaceholderText("Buscar cliente por nombre, DUI/NIT, NRC…")
        layout.addWidget(self.cli_search)
        self.cli_results = QListWidget()
        self.cli_results.addItem("Escribe para buscar…")
        self.cli_results.item(0).setFlags(Qt.NoItemFlags)
        layout.addWidget(self.cli_results)

        self.nomb_recibe = QLineEdit()
        self.docu_recibe = QLineEdit()
        self.nrc_recibe = QLineEdit()
        self.ext_obs = QPlainTextEdit()
        for label, widget in [
            ("Nombre recibe:", self.nomb_recibe),
            ("Documento recibe:", self.docu_recibe),
            ("NRC:", self.nrc_recibe),
            ("Observaciones:", self.ext_obs),
        ]:
            row = QHBoxLayout()
            row.addWidget(QLabel(label))
            row.addWidget(widget)
            layout.addLayout(row)

        self.tipo_doc_recibe = "13"

        # Search handlers and timers
        self.emp_timer = QTimer(self)
        self.emp_timer.setSingleShot(True)
        self.emp_timer.setInterval(250)
        self.emp_search.textChanged.connect(self.emp_timer.start)
        self.emp_timer.timeout.connect(self._buscar_empleado)
        self.emp_results.itemActivated.connect(self._seleccionar_empleado)
        self.emp_results.itemClicked.connect(self._seleccionar_empleado)

        self.cli_timer = QTimer(self)
        self.cli_timer.setSingleShot(True)
        self.cli_timer.setInterval(250)
        self.cli_search.textChanged.connect(self.cli_timer.start)
        self.cli_timer.timeout.connect(self._buscar_cliente)
        self.cli_results.itemActivated.connect(self._seleccionar_cliente)
        self.cli_results.itemClicked.connect(self._seleccionar_cliente)

        for w in [
            self.emp_search,
            self.emp_results,
            self.cli_search,
            self.cli_results,
        ]:
            w.installEventFilter(self)

    def _populate_results(self, widget, items, formatter):
        widget.clear()
        if not items:
            widget.addItem("Sin resultados. Puedes escribir manualmente.")
            widget.item(0).setFlags(Qt.NoItemFlags)
            return
        for itm in items:
            text, data = formatter(itm)
            item = QListWidgetItem(text)
            item.setData(Qt.UserRole, data)
            widget.addItem(item)
        widget.setCurrentRow(0)

    def _buscar_empleado(self):
        text = self.emp_search.text().strip()
        if not text:
            self.emp_results.clear()
            self.emp_results.addItem("Escribe para buscar…")
            self.emp_results.item(0).setFlags(Qt.NoItemFlags)
            return
        try:
            empleados = self.db.get_trabajadores(search=text)
        except Exception:
            empleados = []
        self._populate_results(
            self.emp_results,
            empleados,
            lambda e: (
                f"{e.get('nombre', '')} - {e.get('dui') or e.get('nit') or ''}",
                e,
            ),
        )

    def _seleccionar_empleado(self, item):
        data = item.data(Qt.UserRole) if item else None
        if isinstance(data, dict):
            self.nomb_entrega.setText(data.get("nombre", ""))
            doc = data.get("dui") or data.get("nit") or ""
            self.docu_entrega.setText(limpiar_doc(doc))

    def _buscar_cliente(self):
        text = self.cli_search.text().strip()
        if not text:
            self.cli_results.clear()
            self.cli_results.addItem("Escribe para buscar…")
            self.cli_results.item(0).setFlags(Qt.NoItemFlags)
            return
        try:
            clientes = self.db.get_clientes(search=text)
        except Exception:
            clientes = []
        self._populate_results(
            self.cli_results,
            clientes,
            lambda c: (
                f"{c.get('nombre', '')} - {c.get('dui') or c.get('nit') or c.get('nrc') or ''}",
                c,
            ),
        )

    def _seleccionar_cliente(self, item):
        data = item.data(Qt.UserRole) if item else None
        if isinstance(data, dict):
            self.cli_data = data
            self.nomb_recibe.setText(data.get("nombre", ""))
            nrc = data.get("nrc") or ""
            if nrc:
                self.docu_recibe.setText(limpiar_doc(data.get("nit") or ""))
                self.nrc_recibe.setText(limpiar_doc(nrc))
                self.tipo_doc_recibe = "36"
            else:
                doc = data.get("dui") or data.get("nit") or ""
                self.docu_recibe.setText(limpiar_doc(doc))
                self.nrc_recibe.clear()
                self.tipo_doc_recibe = "13"
        else:
            self.cli_data = None

    def eventFilter(self, obj, event):
        if event.type() == QEvent.KeyPress:
            if obj in (self.emp_search, self.cli_search) and event.key() in (
                Qt.Key_Down,
                Qt.Key_Up,
            ):
                lst = self.emp_results if obj is self.emp_search else self.cli_results
                if lst.count():
                    lst.setFocus()
                    lst.setCurrentRow(0)
                    return True
            if obj in (self.emp_results, self.cli_results) and event.key() in (
                Qt.Key_Return,
                Qt.Key_Enter,
            ):
                current = obj.currentItem()
                if current:
                    obj.itemActivated.emit(current)
                    return True
        return super().eventFilter(obj, event)

    def get_data(self):
        return {
            "nombEntrega": self.nomb_entrega.text(),
            "docuEntrega": limpiar_doc(self.docu_entrega.text()),
            "nombRecibe": self.nomb_recibe.text(),
            "docuRecibe": limpiar_doc(self.docu_recibe.text()),
            "nrcRecibe": limpiar_doc(self.nrc_recibe.text()),
            "tipoDocRecibe": self.tipo_doc_recibe,
            "observaciones": self.ext_obs.toPlainText(),
        }

    def validate(self) -> bool:
        checks = [
            self.nomb_entrega.text().strip(),
            limpiar_doc(self.docu_entrega.text()),
            self.nomb_recibe.text().strip(),
            limpiar_doc(self.docu_recibe.text()),
        ]
        if not all(checks):
            QMessageBox.warning(
                self,
                "Nota",
                "Todos los campos de entrega/recepción son obligatorios",
            )
            return False
        doc = solo_digitos(self.docu_recibe.text())
        if self.tipo_doc_recibe == "36":
            if len(doc) != 14:
                QMessageBox.warning(
                    self, "Nota", "NIT debe tener 14 dígitos (sin guiones)"
                )
                return False
            nrc = solo_digitos(self.nrc_recibe.text())
            if len(nrc) not in (6, 7):
                QMessageBox.warning(
                    self, "Nota", "NRC requerido (6–7 dígitos)"
                )
                return False
        else:
            if len(doc) != 9:
                QMessageBox.warning(
                    self, "Nota", "DUI debe tener 9 dígitos (sin guiones)"
                )
                return False
        return True


class NotaRemisionExtDialog(QDialog):
    """Diálogo que envuelve :class:`NotaRemisionExtWidget` con encabezado."""

    def __init__(self, db, factura=None, parent=None):
        super().__init__(parent)
        self.db = db
        self.factura = factura or {}
        self.setWindowTitle("Datos de entrega")
        self._build_ui()

    def _build_ui(self):
        layout = QVBoxLayout(self)

        if self.factura:
            ident = self.factura.get("identificacion", {})
            receptor = self.factura.get("receptor", {})
            resumen = self.factura.get("resumen", {})
            tipo = ident.get("tipoDte")
            numero = ident.get("numeroControl")
            fecha = ident.get("fecEmi")
            uuid = (ident.get("codigoGeneracion") or "")[:8]
            cliente = receptor.get("nombre") or receptor.get("nombreComercial") or ""
            total = resumen.get("montoTotalOperacion") or resumen.get("totalPagar")
            header = QHBoxLayout()
            header.addWidget(QLabel(f"Factura origen: {tipo} {numero} {fecha} {uuid}"))
            header.addWidget(QLabel(f"Cliente: {cliente}"))
            if total is not None:
                header.addWidget(QLabel(f"Total: {total}"))
            layout.addLayout(header)

        self.panel = NotaRemisionExtWidget(self.db, self)
        layout.addWidget(self.panel)
        # Expose fields for backward compatibility/tests
        self.nomb_entrega = self.panel.nomb_entrega
        self.docu_entrega = self.panel.docu_entrega
        self.nomb_recibe = self.panel.nomb_recibe
        self.docu_recibe = self.panel.docu_recibe
        self.ext_obs = self.panel.ext_obs
        self._seleccionar_empleado = self.panel._seleccionar_empleado
        self._seleccionar_cliente = self.panel._seleccionar_cliente

        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)

    def accept(self):
        if not self.panel.validate():
            return
        super().accept()

    def get_data(self):
        return self.panel.get_data()

class FacturacionTab(QWidget):
    """Tab para gestionar facturas y notas."""

    def __init__(self, manager, parent=None):
        super().__init__(parent)
        self.manager = manager
        self.email_thread = None
        self._setup_ui()
        # Clean up any stale invoice references before loading
        # documents into the table. This prevents entries tied to
        # deleted sales or missing files from showing as "Sin venta".
        self._get_invoices_from_db()
        self.load_invoices()

    def _setup_ui(self):
        main_layout = QHBoxLayout(self)

        left_layout = QVBoxLayout()

        filter_layout = QHBoxLayout()
        self.search_bar = QLineEdit()
        self.search_bar.setPlaceholderText("Buscar número o cliente")
        filter_layout.addWidget(self.search_bar)

        self.client_filter = QComboBox()
        self.client_filter.addItem("Todos", None)
        for c in self.manager._clientes:
            self.client_filter.addItem(c.get("nombre", ""), c.get("id"))
        filter_layout.addWidget(self.client_filter)

        self.vendedor_filter = QComboBox()
        self.vendedor_filter.addItem("Todos", None)
        for v in self.manager.db.get_trabajadores(solo_vendedores=True):
            self.vendedor_filter.addItem(v.get("nombre", ""), v.get("id"))
        filter_layout.addWidget(self.vendedor_filter)

        self.tipo_filter = QComboBox()
        self.tipo_filter.addItems([
            "Todos",
            "Consumidor final",
            "Crédito fiscal",
            "Nota de débito",
        ])
        filter_layout.addWidget(self.tipo_filter)

        self.date_filter_cb = QCheckBox("Filtrar por fecha")
        self.quick_range = QComboBox()
        self.quick_range.addItems(["Personalizado", "Esta semana", "Este mes", "Este año"])
        self.date_from = QDateEdit(QDate.currentDate().addYears(-2))
        self.date_from.setCalendarPopup(True)
        self.date_to = QDateEdit(QDate.currentDate())
        self.date_to.setCalendarPopup(True)
        self.quick_range.setEnabled(False)
        self.date_from.setEnabled(False)
        self.date_to.setEnabled(False)
        for w in [self.date_filter_cb, self.quick_range, QLabel("Desde"), self.date_from,
                  QLabel("Hasta"), self.date_to]:
            filter_layout.addWidget(w)
        self.date_filter_cb.toggled.connect(self._toggle_date_filter)
        self.quick_range.currentIndexChanged.connect(self._apply_quick_range)
        self.update_btn = QPushButton("Actualizar")
        filter_layout.addWidget(self.update_btn)
        filter_layout.addStretch(1)
        left_layout.addLayout(filter_layout)

        self.table = QTableWidget(0, 5)
        self.table.setHorizontalHeaderLabels(["ID", "Fecha", "Cliente", "Total", "Estado"])
        self.table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        left_layout.addWidget(self.table)

        btns = QHBoxLayout()
        # Botón para crear notas asociadas a la factura seleccionada
        self.btn_nota = QPushButton("Nota crédito / débito")
        self.btn_nota.clicked.connect(self.abrir_dialogo_tipo_nota)
        self.btn_remision = QPushButton("Nota remisión")
        self.btn_remision.clicked.connect(self.abrir_dialogo_nota_remision)
        self.btn_enviar = QPushButton("Enviar")
        self.btn_enviar.setEnabled(False)
        self.btn_abrir_pdf = QPushButton("Abrir PDF")
        self.btn_eliminar = QPushButton("Eliminar")
        self.btn_eliminar.setStyleSheet(
            "background-color: #b71c1c; color: #fff; border-radius: 6px;",
        )
        btns.addWidget(self.btn_nota)
        btns.addWidget(self.btn_remision)
        btns.addWidget(self.btn_enviar)
        btns.addWidget(self.btn_abrir_pdf)
        btns.addWidget(self.btn_eliminar)
        btns.addStretch(1)
        left_layout.addLayout(btns)

        main_layout.addLayout(left_layout, 3)

        preview_layout = QVBoxLayout()
        self.preview_label = QLabel("Previsualización del PDF")
        self.preview_label.setAlignment(Qt.AlignCenter)
        self.preview_label.setStyleSheet("background:#DDD; padding:20px;")
        preview_layout.addWidget(self.preview_label)
        main_layout.addLayout(preview_layout, 2)

        # Connect signals
        self.update_btn.clicked.connect(self.refresh_and_reload)
        self.search_bar.textChanged.connect(self.load_invoices)
        self.client_filter.currentIndexChanged.connect(self.load_invoices)
        self.vendedor_filter.currentIndexChanged.connect(self.load_invoices)
        self.tipo_filter.currentIndexChanged.connect(self.load_invoices)
        self.date_from.dateChanged.connect(self.load_invoices)
        self.date_to.dateChanged.connect(self.load_invoices)
        self.table.itemSelectionChanged.connect(self.show_invoice)
        self.table.itemSelectionChanged.connect(self._update_send_btn)
        self.table.itemDoubleClicked.connect(self.mostrar_detalle_factura)

        self.btn_enviar.clicked.connect(self.send_selected_invoice)
        self.btn_abrir_pdf.clicked.connect(self.open_pdf)
        self.btn_eliminar.clicked.connect(self.delete_files)

    def _toggle_date_filter(self, checked):
        self.quick_range.setEnabled(checked)
        custom = self.quick_range.currentIndex() == 0
        self.date_from.setEnabled(checked and custom)
        self.date_to.setEnabled(checked and custom)
        if checked:
            self._apply_quick_range()
        else:
            self.load_invoices()

    def _apply_quick_range(self):
        if not self.date_filter_cb.isChecked():
            return
        option = self.quick_range.currentText()
        today = date.today()
        if option == "Esta semana":
            start = today - timedelta(days=today.weekday())
            end = start + timedelta(days=6)
            self.date_from.setDate(QDate(start))
            self.date_to.setDate(QDate(end))
            self.date_from.setEnabled(False)
            self.date_to.setEnabled(False)
        elif option == "Este mes":
            start = today.replace(day=1)
            if today.month == 12:
                end = date(today.year, 12, 31)
            else:
                end = date(today.year, today.month + 1, 1) - timedelta(days=1)
            self.date_from.setDate(QDate(start))
            self.date_to.setDate(QDate(end))
            self.date_from.setEnabled(False)
            self.date_to.setEnabled(False)
        elif option == "Este año":
            start = date(today.year, 1, 1)
            end = date(today.year, 12, 31)
            self.date_from.setDate(QDate(start))
            self.date_to.setDate(QDate(end))
            self.date_from.setEnabled(False)
            self.date_to.setEnabled(False)
        else:
            self.date_from.setEnabled(True)
            self.date_to.setEnabled(True)
        self.load_invoices()

    def refresh_filters(self):
        """Update client and vendor filter combos with latest data."""
        self.client_filter.blockSignals(True)
        self.vendedor_filter.blockSignals(True)

        current_client = self.client_filter.currentData()
        current_vend = self.vendedor_filter.currentData()

        self.client_filter.clear()
        self.client_filter.addItem("Todos", None)
        for c in self.manager._clientes:
            self.client_filter.addItem(c.get("nombre", ""), c.get("id"))

        self.vendedor_filter.clear()
        self.vendedor_filter.addItem("Todos", None)
        for v in self.manager.db.get_trabajadores(solo_vendedores=True):
            self.vendedor_filter.addItem(v.get("nombre", ""), v.get("id"))

        def _restore(combo, value):
            if value is None:
                combo.setCurrentIndex(0)
                return
            for i in range(combo.count()):
                if combo.itemData(i) == value:
                    combo.setCurrentIndex(i)
                    return
            combo.setCurrentIndex(0)

        _restore(self.client_filter, current_client)
        _restore(self.vendedor_filter, current_vend)

        self.client_filter.blockSignals(False)
        self.vendedor_filter.blockSignals(False)

    def _get_invoices_from_db(self):
        """Return invoice entries stored in the database.

        Stale records whose sale no longer exists or whose PDF file is
        missing are removed to keep the table tidy. The remaining rows
        are returned as a list of dictionaries compatible with
        ``load_invoices``.
        """

        cur = self.manager.db.cursor
        cur.execute(
            "SELECT id, venta_id, tipo, ruta, fecha_creacion FROM facturas_pdf"
        )
        records = cur.fetchall()
        rows = []
        to_delete = []
        for rec in records:
            venta = cur.execute(
                """
                SELECT v.id, v.fecha, v.total, v.estado, c.nombre AS cliente
                FROM ventas v
                LEFT JOIN clientes c ON c.id = v.cliente_id
                WHERE v.id=?
                """,
                (rec["venta_id"],),
            ).fetchone()
            ruta = rec["ruta"]
            if not venta or not ruta or not os.path.exists(ruta):
                to_delete.append((rec["id"],))
                continue
            fecha_creacion = rec["fecha_creacion"] or ""
            fdate = None
            if fecha_creacion:
                try:
                    fdate = datetime.strptime(fecha_creacion, "%Y-%m-%d %H:%M:%S")
                except Exception:
                    fdate = None
            fecha_str = fdate.strftime("%Y-%m-%d %H:%M") if fdate else fecha_creacion
            rows.append(
                {
                    "row_type": "venta",
                    "id": venta["id"],
                    "name": os.path.splitext(os.path.basename(ruta))[0],
                    "fecha": fecha_str,
                    "_parsed_fecha": fdate,
                    "cliente": venta["cliente"] or "",
                    "total": venta["total"],
                    "estado": venta["estado"],
                    "tipo": rec["tipo"],
                }
            )
        if to_delete:
            cur.executemany("DELETE FROM facturas_pdf WHERE id=?", to_delete)
            self.manager.db.conn.commit()
        return rows

    def refresh_and_reload(self):
        """Refresh manager data and reload invoices."""
        self.manager.refresh_data()
        self.refresh_filters()
        self.load_invoices()

    def load_invoices(self):
        search = self.search_bar.text().lower() if hasattr(self, "search_bar") else ""
        if self.date_filter_cb.isChecked():
            d_from = self.date_from.date().toPyDate()
            d_to = self.date_to.date().toPyDate()
        else:
            d_from = d_to = None
        tipo = self.tipo_filter.currentText()

        rows = self._scan_documents()
        for r in list(rows):
            fdate = r.get("_parsed_fecha")
            if self.date_filter_cb.isChecked():
                if d_from and fdate and fdate.date() < d_from:
                    rows.remove(r)
                    continue
                if d_to and fdate and fdate.date() > d_to:
                    rows.remove(r)
                    continue
            if tipo != "Todos" and r.get("tipo") != tipo:
                rows.remove(r)
                continue
            cliente = r.get("cliente", "")
            if search and search not in r.get("name", "").lower() and search not in cliente.lower():
                rows.remove(r)

        rows.sort(
            key=lambda r: (
                r.get("_parsed_fecha") is None,
                -(r.get("_parsed_fecha").timestamp() if r.get("_parsed_fecha") else 0),
            )
        )

        self.table.setRowCount(len(rows))
        for row, v in enumerate(rows):
            codigo = v.get("codigo", "")
            tipo = v.get("tipo", "")
            text_id = f"{codigo} {tipo}".strip() if codigo else v.get("name", "")
            self.table.setItem(row, 0, QTableWidgetItem(text_id))
            self.table.setItem(row, 1, QTableWidgetItem(v.get("fecha", "")))
            self.table.setItem(row, 2, QTableWidgetItem(v.get("cliente", "")))
            total = v.get("total")
            signo = v.get("sign", 1)
            if isinstance(total, (int, float)):
                pref = "+" if signo >= 0 else "−"
                self.table.setItem(row, 3, QTableWidgetItem(f"{pref}${abs(total):.2f}"))
            else:
                self.table.setItem(row, 3, QTableWidgetItem(""))
            self.table.setItem(row, 4, QTableWidgetItem(v.get("estado", "")))
            for col in range(5):
                item = self.table.item(row, col)
                if item:
                    item.setData(Qt.UserRole, v)
        if rows:
            self.table.selectRow(0)
        self._update_send_btn()

    def _scan_documents(self):
        result = []
        folders = [
            CF_DIR,
            CREDITO_DIR,
            NOTAS_DEBITO_DIR,
            NOTAS_CREDITO_DIR,
            NOTAS_REMISION_DIR,
        ] + ADDITIONAL_DIRS
        files = {}
        for folder in folders:
            if not os.path.isdir(folder):
                continue
            if folder == CF_DIR or "consumidor_final" in folder:
                tipo = "Consumidor final"
            elif folder == CREDITO_DIR or "credito_fiscal" in folder:
                tipo = "Crédito fiscal"
            elif folder == NOTAS_DEBITO_DIR or "notas_debito" in folder:
                tipo = "Nota de débito"
            elif folder == NOTAS_CREDITO_DIR or "notas_credito" in folder:
                tipo = "Nota de crédito"
            elif folder == NOTAS_REMISION_DIR or "notas_remision" in folder:
                tipo = "Nota de remisión"
            else:
                tipo = None
            for root, _dirs, fnames in os.walk(folder):
                for fname in fnames:
                    base, ext = os.path.splitext(fname)
                    if ext.lower() not in (".pdf", ".json"):
                        continue
                    if not DOC_PATTERN.match(base):
                        continue
                    entry = files.setdefault(base, {"tipo": tipo})
                    entry.setdefault(ext.lower(), os.path.join(root, fname))
                    entry.setdefault("tipo", tipo or entry.get("tipo"))

        for base, paths in files.items():
            pdf = paths.get(".pdf")
            js = paths.get(".json")
            tipo = paths.get("tipo")
            estado = "Completa" if pdf and js else "Incompleta"
            numero = base
            fecha = ""
            cliente = ""
            total = None
            signo = 1
            fdate = None
            codigo = None
            if js and os.path.exists(js):
                try:
                    with open(js, "r", encoding="utf-8") as fh:
                        data = json.load(fh)
                    ident = data.get("identificacion", {})
                    numero = ident.get("numeroControl", numero)
                    codigo = ident.get("tipoDte")
                    fecha = ident.get("fecEmi", "")
                    hora = ident.get("horEmi", "")
                    cliente = data.get("receptor", {}).get("nombre", "")

                    resumen = data.get("resumen", {})
                    if tipo in ("Nota de crédito", "Nota de débito"):
                        total = resumen.get("montoTotalOperacion")
                        signo = -1 if tipo == "Nota de crédito" else 1
                    else:
                        total = resumen.get("totalPagar")
                    try:
                        total = abs(float(total))
                    except (TypeError, ValueError):
                        total = None

                    if fecha:
                        try:
                            if hora:
                                fdate = datetime.strptime(
                                    f"{fecha} {hora}", "%Y-%m-%d %H:%M:%S"
                                )
                                fecha = fdate.strftime("%Y-%m-%d %H:%M")
                            else:
                                fdate = datetime.strptime(fecha, "%Y-%m-%d")
                                fecha = fdate.strftime("%Y-%m-%d")
                        except Exception:
                            fdate = None
                except Exception:
                    estado = "Incompleta"
            result.append(
                {
                    "row_type": "orphan",
                    "name": numero,
                    "codigo": codigo,
                    "pdf": pdf,
                    "json": js,
                    "fecha": fecha,
                    "_parsed_fecha": fdate,
                    "estado": estado,
                    "cliente": cliente,
                    "total": total,
                    "sign": signo,
                    "tipo": tipo,
                }
            )
        return result


    def _selected_entry(self):
        selected_rows = self.table.selectionModel().selectedRows()
        if not selected_rows:
            return None
        row = selected_rows[0].row()
        item = self.table.item(row, 0)
        return item.data(Qt.UserRole) if item else None

    def _selected_factura(self):
        """Return information about the selected invoice.

        The returned dictionary contains at least the JSON path and
        control number. If the invoice is associated with a sale the
        corresponding ``venta_id`` is also included. ``None`` is
        returned if the selection does not correspond to a valid
        invoice.
        """

        data = self._selected_entry()
        if not data:
            return None
        rtype = data.get("row_type")
        if rtype == "venta":
            venta_id = data.get("id")
            pdf_path = self.manager.db.get_factura_pdf(venta_id)
            if not pdf_path:
                return None
            json_path = os.path.splitext(pdf_path)[0] + ".json"
            if not os.path.exists(json_path):
                return None
            control = None
            try:
                with open(json_path, "r", encoding="utf-8") as fh:
                    jdata = json.load(fh)
                control = jdata.get("identificacion", {}).get("numeroControl")
            except Exception:
                pass
            return {"venta_id": venta_id, "json": json_path, "control": control}
        if rtype == "orphan":
            json_path = data.get("json")
            pdf_path = data.get("pdf")
            if not json_path or not os.path.exists(json_path):
                return None
            if not pdf_path or not os.path.exists(pdf_path):
                return None
            return {
                "venta_id": data.get("id"),
                "json": json_path,
                "control": data.get("name"),
            }
        return None

    def _update_send_btn(self):
        entry = self._selected_entry()
        enabled = False
        if entry:
            rtype = entry.get("row_type")
            if rtype in ("venta", "ticket"):
                enabled = True
            elif rtype == "orphan" and entry.get("json") and entry.get("estado") != "Incompleta":
                enabled = True
        self.btn_enviar.setEnabled(enabled)

    def _show_validation_errors(self, errors, json_path):
        """Display validation errors and allow opening a report."""
        msg = QMessageBox(self)
        msg.setWindowTitle("Enviar a Hacienda")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("El DTE contiene errores de validación:")
        msg.setInformativeText("\n".join(f"- {e}" for e in errors))
        open_btn = msg.addButton("Abrir reporte", QMessageBox.ActionRole)
        msg.addButton(QMessageBox.Close)
        msg.exec_()
        if msg.clickedButton() == open_btn and json_path:
            report_path = os.path.splitext(json_path)[0] + ".md"
            with open(report_path, "w", encoding="utf-8") as fh:
                fh.write("# Errores de validación\n\n")
                for e in errors:
                    fh.write(f"- {e}\n")
            QDesktopServices.openUrl(QUrl.fromLocalFile(report_path))

    def _show_hacienda_response(self, resp: dict) -> None:
        """Show a message box summarizing Hacienda's response."""
        resp = resp or {}
        estado = resp.get("estado", "").upper()
        if estado in {"PROCESADO", "RECIBIDO"}:
            QMessageBox.information(
                self,
                "Enviar a Hacienda",
                "Documento enviado y recibido correctamente",
            )
        elif estado == "TRANSMITIDO":
            QMessageBox.information(
                self,
                "Enviar a Hacienda",
                "Documento transmitido correctamente",
            )
        else:
            detalle = resp.get("errores") or resp.get("detalle") or "Error"
            QMessageBox.critical(
                self,
                "Enviar a Hacienda",
                f"Fallo: {detalle}",
            )

    def send_selected_invoice(self):
        entry = self._selected_entry()
        if not entry:
            QMessageBox.warning(self, "Enviar", "Seleccione un documento")
            return

        factura = None
        rtype = entry.get("row_type")
        if rtype in ("venta", "orphan"):
            factura = self._selected_factura()
            if not factura:
                QMessageBox.warning(self, "Enviar", "Seleccione una factura válida")
                return

        dialog = SendOptionsDialog(self)
        dialog.email_cb.setChecked(True)
        if dialog.exec_() != QDialog.Accepted:
            return

        if dialog.email_cb.isChecked():
            if rtype == "venta" and factura:
                self._send_invoice_email(factura.get("venta_id"))
            elif rtype == "ticket":
                self._send_ticket_email(entry.get("id"))
            elif rtype == "orphan" and factura:
                self._send_orphan_email(entry)
        if dialog.hacienda_cb.isChecked():
            if rtype == "orphan" and factura:
                json_path = factura.get("json")
                try:
                    resp = dte.transmitir_dte_orphan(self.manager.db, json_path)
                    self._show_hacienda_response(resp)
                except dte.DTEValidationError as exc:
                    self._show_validation_errors(exc.errors, exc.json_path)
                except Exception as exc:
                    QMessageBox.critical(
                        self, "Enviar a Hacienda", str(exc)
                    )
            else:
                tipo = "03" if rtype == "ticket" else "01"
                try:
                    resp = transmitir_dte(
                        self.manager.db, entry.get("id"), tipo_dte=tipo
                    )
                    self._show_hacienda_response(resp)
                except dte.DTEValidationError as exc:
                    self._show_validation_errors(exc.errors, exc.json_path)
                except Exception as exc:
                    QMessageBox.critical(
                        self, "Enviar a Hacienda", str(exc)
                    )

    def open_pdf(self):
        entry = self._selected_entry()
        if not entry:
            QMessageBox.warning(self, "Abrir PDF", "No se ha seleccionado ninguna factura.")
            return

        pdf_path = None
        rtype = entry.get("row_type")
        if rtype == "venta":
            venta_id = entry.get("id")
            pdf_path = self.manager.db.get_factura_pdf(venta_id)
            if not pdf_path or not os.path.exists(pdf_path):
                pdf_path = self._generate_invoice_pdf(venta_id)
        elif rtype == "ticket":
            venta_id = entry.get("id")
            pdf_path = self.manager.db.get_ticket_pdf(venta_id)
            if not pdf_path or not os.path.exists(pdf_path):
                pdf_path = self._generate_ticket_pdf(venta_id)
        else:
            pdf_path = entry.get("pdf")

        if pdf_path and os.path.exists(pdf_path):
            QDesktopServices.openUrl(QUrl.fromLocalFile(pdf_path))
        else:
            QMessageBox.warning(self, "Abrir PDF", "No se encontró el archivo PDF.")

    def mostrar_detalle_factura(self, item=None):
        factura = self._selected_factura()
        if not factura:
            QMessageBox.warning(self, "Detalle", "Seleccione una factura válida")
            return
        json_path = factura.get("json")
        if not json_path or not os.path.exists(json_path):
            QMessageBox.warning(self, "Detalle", "No se encontró el archivo JSON")
            return
        try:
            with open(json_path, "r", encoding="utf-8") as fh:
                data = json.load(fh)
        except Exception:
            QMessageBox.warning(self, "Detalle", "Error al leer el archivo JSON")
            return
        items = data.get("cuerpoDocumento") or []
        resumen = data.get("resumen") or {}
        dlg = InvoiceDetailDialog(items, resumen, self)
        dlg.exec_()

    def _send_invoice_email(self, venta_id):
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            QMessageBox.warning(self, "Enviar por correo", "No se encontró la venta seleccionada.")
            return

        cliente_email = ""
        if venta.get("cliente_id"):
            cli = next((c for c in self.manager._clientes if c["id"] == venta["cliente_id"]), None)
            if cli:
                cliente_email = cli.get("email", "")
        if not cliente_email:
            QMessageBox.warning(self, "Enviar por correo", "El cliente no tiene correo registrado.")
            return

        pdf_path = self.manager.db.get_factura_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            pdf_path = self._generate_invoice_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            QMessageBox.warning(self, "Enviar por correo", "No se pudo generar el PDF.")
            return
        json_path = os.path.splitext(pdf_path)[0] + ".json"
        if not os.path.exists(json_path):
            pdf_path = self._generate_invoice_pdf(venta_id)
            json_path = os.path.splitext(pdf_path)[0] + ".json"
            if not os.path.exists(json_path):
                QMessageBox.warning(self, "Enviar por correo", "No se encontró el JSON firmado.")
                return

        creds = {}
        if os.path.exists(DATOS_NEGOCIO_PATH):
            try:
                with open(DATOS_NEGOCIO_PATH, "r", encoding="utf-8") as f:
                    creds = json.load(f)
            except Exception:
                creds = {}
        server = creds.get("smtp_server")
        port = creds.get("smtp_port")
        user = creds.get("email_usuario")
        password = os.getenv("INVENTARIO_EMAIL_PASSWORD") or creds.get("email_contrasena")
        if not all([server, port, user, password]):
            QMessageBox.warning(self, "Enviar por correo", "Credenciales SMTP incompletas.")
            return

        subject = "Factura"
        body = (
            "Adjunto se envía la representación gráfica en PDF y el documento firmado en formato JSON"
        )

        self.btn_enviar.setEnabled(False)
        self.email_thread = EmailSender(
            server,
            port,
            user,
            password,
            cliente_email,
            subject,
            body,
            [pdf_path, json_path],
        )
        self.email_thread.finished.connect(self._on_email_sent)
        self.email_thread.start()

    def _send_orphan_email(self, entry):
        json_path = entry.get("json")
        pdf_path = entry.get("pdf")
        dest, ok = QInputDialog.getText(
            self, "Enviar por correo", "Correo del destinatario:")
        if not ok or not dest:
            return
        if not json_path or not os.path.exists(json_path):
            QMessageBox.warning(self, "Enviar por correo", "No se encontró el JSON.")
            return
        attachments = [json_path]
        if pdf_path and os.path.exists(pdf_path):
            attachments.insert(0, pdf_path)
        else:
            QMessageBox.warning(
                self, "Enviar por correo", "No se encontró PDF. Solo se adjuntará el JSON."
            )
        creds = {}
        if os.path.exists(DATOS_NEGOCIO_PATH):
            try:
                with open(DATOS_NEGOCIO_PATH, "r", encoding="utf-8") as f:
                    creds = json.load(f)
            except Exception:
                creds = {}
        server = creds.get("smtp_server")
        port = creds.get("smtp_port")
        user = creds.get("email_usuario")
        password = os.getenv("INVENTARIO_EMAIL_PASSWORD") or creds.get("email_contrasena")
        if not all([server, port, user, password]):
            QMessageBox.warning(self, "Enviar por correo", "Credenciales SMTP incompletas.")
            return
        subject = "Factura"
        body = (
            "Adjunto se envía la representación gráfica en PDF y el documento firmado en formato JSON"
        )
        self.btn_enviar.setEnabled(False)
        self.email_thread = EmailSender(
            server,
            port,
            user,
            password,
            dest,
            subject,
            body,
            attachments,
        )
        self.email_thread.finished.connect(self._on_email_sent)
        self.email_thread.start()

    def _on_email_sent(self, success, message):
        self.btn_enviar.setEnabled(True)
        if success:
            QMessageBox.information(self, "Enviar por correo", message)
        else:
            QMessageBox.critical(self, "Enviar por correo", message)
        self.email_thread = None

    def create_ticket(self):
        entry = self._selected_entry()
        if not entry or entry.get("row_type") not in ("venta", "ticket"):
            raise ValueError("No sale selected")
        venta_id = entry.get("id")
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        detalles = self.manager.db.get_detalles_venta(venta_id)
        extra = {}
        raw_extra = venta.get("extra") if venta else None
        if raw_extra:
            try:
                extra = json.loads(raw_extra)
            except Exception:
                extra = {}
        fname, _ = QFileDialog.getSaveFileName(
            self,
            "Guardar ticket",
            "ticket.pdf",
            "PDF (*.pdf)",
            options=QFileDialog.DontUseNativeDialog,
        )
        if not fname:
            return
        generar_ticket_personalizado(venta, detalles, fname, dte_data=extra)
        QMessageBox.information(self, "Ticket", "Ticket generado correctamente")

    def abrir_dialogo_tipo_nota(self):
        factura = self._selected_factura()
        if not factura:
            QMessageBox.warning(self, "Nota", "Seleccione una factura")
            return
        # Diálogo inicial para elegir el tipo de nota
        dialog = QDialog(self)
        dialog.setWindowTitle("Nota crédito / débito")
        layout = QVBoxLayout(dialog)

        radio_credito = QRadioButton("Nota de crédito", dialog)
        radio_debito = QRadioButton("Nota de débito", dialog)
        radio_credito.setChecked(True)
        layout.addWidget(radio_credito)
        layout.addWidget(radio_debito)

        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        # Cambiar el texto del botón de aceptación a "Continuar"
        buttons.button(QDialogButtonBox.Ok).setText("Continuar")
        buttons.accepted.connect(dialog.accept)
        buttons.rejected.connect(dialog.reject)
        layout.addWidget(buttons)

        if dialog.exec_() == QDialog.Accepted:
            tipo = "credito" if radio_credito.isChecked() else "debito"
            self.create_nota(tipo, factura)

    def abrir_dialogo_nota_remision(self):
        dialog = QDialog(self)
        dialog.setWindowTitle("Nota de remisión")
        layout = QVBoxLayout(dialog)

        radio_factura = QRadioButton("Desde factura", dialog)
        radio_factura.setChecked(True)
        layout.addWidget(radio_factura)

        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttons.button(QDialogButtonBox.Ok).setText("Continuar")
        buttons.accepted.connect(dialog.accept)
        buttons.rejected.connect(dialog.reject)
        layout.addWidget(buttons)

        if dialog.exec_() == QDialog.Accepted:
            self.crear_nota_remision_desde_factura()

    def _guardar_archivos_nota_remision(
        self, nota_json, nota_id=None, transmitir=False
    ):
        resumen_nota = nota_json.get("resumen", {})
        tributos = {t.get("codigo"): t.get("valor", 0) for t in resumen_nota.get("tributos", []) or []}
        venta_data = {
            "sumas": float(resumen_nota.get("subTotalVentas", 0)),
            "descuentos": float(resumen_nota.get("totalDescu", 0)),
            "iva": float(tributos.get("20", 0)),
            "ventas_exentas": float(resumen_nota.get("totalExenta", 0)),
            "ventas_no_sujetas": float(resumen_nota.get("totalNoSuj", 0)),
            "subtotal": float(resumen_nota.get("subTotal", 0)),
            "total": float(resumen_nota.get("montoTotalOperacion", 0)),
            "total_letras": resumen_nota.get("totalLetras", ""),
        }
        detalles_pdf = []
        for d in nota_json.get("cuerpoDocumento", []) or []:
            detalles_pdf.append(
                {
                    "cantidad": float(d.get("cantidad", 1)),
                    "descripcion": d.get("descripcion", ""),
                    "precio_unitario": float(d.get("precioUni", 0)),
                    "ventas_gravadas": float(d.get("ventaGravada", 0)),
                    "ventas_exentas": float(d.get("ventaExenta", 0)),
                    "ventas_no_sujetas": float(d.get("ventaNoSuj", 0)),
                }
            )
        cliente = nota_json.get("receptor", {}) or {}
        extension = nota_json.get("extension", {}) or {}
        pdf_path, json_path = get_dte_document_paths(
            nota_json["identificacion"].get("fecEmi"),
            cliente.get("nombre") or cliente.get("nombreComercial") or "",
            nota_json["identificacion"].get("numeroControl"),
            "NotaRemision",
        )
        generar_nota_remision_pdf(
            venta_data, detalles_pdf, cliente, extension, archivo=str(pdf_path)
        )
        sign_and_save(nota_json, str(json_path))
        if transmitir and nota_id is not None:
            try:
                resp = enviar_nota_remision(self.manager.db, nota_id)
                if resp and resp.get("estado") == "Error":
                    QMessageBox.critical(self, "Nota", resp.get("detalle", "Error"))
                else:
                    QMessageBox.information(
                        self, "Nota", "Nota registrada y transmitida"
                    )
            except dte.DTEValidationError as exc:
                self._show_validation_errors(exc.errors, exc.json_path)
            except Exception as exc:
                QMessageBox.critical(self, "Nota", str(exc))

    def crear_nota_remision_desde_factura(self):
        factura = self._selected_factura()
        if not factura:
            QMessageBox.warning(self, "Nota", "Seleccione una factura")
            return
        venta_id = factura.get("venta_id")
        json_path = factura.get("json")
        try:
            with open(json_path, "r", encoding="utf-8") as fh:
                factura_json = json.load(fh)
        except Exception:
            QMessageBox.warning(self, "Nota", "No se pudo leer la factura")
            return
        if not venta_id:
            QMessageBox.warning(self, "Nota", "Factura sin venta asociada")
        dialog = NotaRemisionExtDialog(self.manager.db, factura=factura_json, parent=self)
        if dialog.exec_() != QDialog.Accepted:
            return
        extension = dialog.get_data()
        fecha = QDate.currentDate().toString("yyyy-MM-dd")
        extra = {"extension": extension}
        if not venta_id:
            extra["factura"] = factura_json
        nota_id = self.manager.db.agregar_nota(
            "remision", venta_id, fecha, 0, "Remision", detalles=extra
        )
        nota_json = generar_nota_remision_desde_db(self.manager.db, nota_id)
        self._guardar_archivos_nota_remision(nota_json)
        QMessageBox.information(self, "Nota", "Nota de remisión generada correctamente")


    def create_nota(self, tipo, factura=None):
        factura = factura or self._selected_factura()
        if not factura:
            QMessageBox.warning(self, "Nota", "Seleccione una factura")
            return
        json_path = factura.get("json")
        venta_id = factura.get("venta_id")
        try:
            with open(json_path, "r", encoding="utf-8") as fh:
                data = json.load(fh)
        except Exception:
            QMessageBox.warning(self, "Nota", "No se pudo leer la factura")
            return

        detalles_venta = []
        for d in data.get("cuerpoDocumento", []) or []:
            detalles_venta.append(
                {
                    "id": d.get("numItem"),
                    "producto_id": d.get("codigo"),
                    "descripcion": d.get("descripcion", ""),
                    "cantidad": float(d.get("cantidad", 0)),
                    "precio_unitario": float(d.get("precioUni", 0)),
                    "descuento": float(d.get("montoDescu", 0)),
                    "descuento_tipo": "$",
                    "ventas_gravadas": float(d.get("ventaGravada", 0)),
                    "ventas_exentas": float(d.get("ventaExenta", 0)),
                    "ventas_no_sujetas": float(d.get("ventaNoSuj", 0)),
                    "precio_unitario_iva": Decimal(str(d.get("ivaItem", 0))),
                    "descuento_iva": Decimal(str(d.get("montoDescu", 0))),
                    "total_linea": Decimal(str(d.get("ventaGravada", 0))),
                }
            )

        detalle_map = {d["id"]: d for d in detalles_venta}

        dialog = NotaDetalleDialog(detalles_venta, tipo, self)
        if dialog.exec_() != QDialog.Accepted:
            return
        monto, motivo, detalles_nota = dialog.get_data()
        for det in detalles_nota or []:
            src = detalle_map.get(det.get("detalle_id"))
            ajuste_total = abs(det.get("ajuste", 0))
            if src and src.get("ventas_gravadas"):
                base = ajuste_total / 1.13
                iva = ajuste_total - base
                det.update({
                    "ventas_gravadas": base,
                    "iva": iva,
                    "precio_unitario": base,
                })
            elif src and src.get("ventas_exentas"):
                det.update({
                    "ventas_exentas": ajuste_total,
                    "iva": 0.0,
                    "precio_unitario": ajuste_total,
                })
            elif src and src.get("ventas_no_sujetas"):
                det.update({
                    "ventas_no_sujetas": ajuste_total,
                    "iva": 0.0,
                    "precio_unitario": ajuste_total,
                })
            else:
                base = ajuste_total / 1.13
                iva = ajuste_total - base
                det.update({
                    "ventas_gravadas": base,
                    "iva": iva,
                    "precio_unitario": base,
                })
        if monto == 0:
            QMessageBox.warning(self, "Nota", "El monto total debe ser diferente de cero")
            return
        fecha = QDate.currentDate().toString("yyyy-MM-dd")
        resumen_factura = data.get("resumen", {}) or {}
        total_original = float(
            resumen_factura.get("totalPagar")
            or resumen_factura.get("montoTotalOperacion")
            or 0
        )
        if tipo == "debito":
            total_ajustado = total_original + monto
        elif tipo == "credito":
            total_ajustado = total_original - monto
        else:
            total_ajustado = total_original
        resumen = (
            f"Total original: {total_original:.2f}\n"
            f"Ajuste: {monto:.2f}\n"
            f"Total ajustado: {total_ajustado:.2f}\n\n"
            "¿Desea continuar?"
        )
        if QMessageBox.question(self, "Confirmar", resumen, QMessageBox.Yes | QMessageBox.No) != QMessageBox.Yes:
            return

        nota_id = self.manager.db.agregar_nota(
            tipo, venta_id, fecha, monto, motivo, detalles=detalles_nota
        )

        detalles_pdf = []
        for det in detalles_nota or []:
            src = detalle_map.get(det.get("detalle_id"))
            if not src:
                continue
            detalle = {
                "cantidad": 1,
                "descripcion": src.get("descripcion", ""),
                "precio_unitario": det.get("precio_unitario", 0),
                "ventas_gravadas": det.get("ventas_gravadas", 0),
                "ventas_exentas": det.get("ventas_exentas", 0),
                "ventas_no_sujetas": det.get("ventas_no_sujetas", 0),
            }
            detalles_pdf.append(detalle)

        if tipo == "credito":
            ratio = None
            if not detalles_pdf:
                ratio = Decimal(str(monto / total_original))
            nota_json = nota_credito_electronica.generar_nce_desde_dte(
                self.manager.db,
                data,
                ratio,
                detalles=detalles_pdf or None,
                motivo=motivo,
            )
        elif tipo == "debito":
            nota_json = generar_nde_desde_dte(
                self.manager.db, data, detalles_pdf or None, monto, motivo
            )
        else:
            nota_json = generar_nota_remision_desde_db(self.manager.db, nota_id)

        resumen_nota = nota_json.get("resumen", {})
        tributos = {t.get("codigo"): t.get("valor", 0) for t in resumen_nota.get("tributos", []) or []}
        venta_data = {
            "sumas": float(resumen_nota.get("subTotalVentas", 0)),
            "descuentos": float(resumen_nota.get("totalDescu", 0)),
            "iva": float(tributos.get("20", 0)),
            "ventas_exentas": float(resumen_nota.get("totalExenta", 0)),
            "ventas_no_sujetas": float(resumen_nota.get("totalNoSuj", 0)),
            "subtotal": float(resumen_nota.get("subTotal", 0)),
            "total": float(resumen_nota.get("montoTotalOperacion", 0)),
            "total_letras": resumen_nota.get("totalLetras", ""),
        }
        if not detalles_pdf:
            detalles_pdf = []
            for d in nota_json.get("cuerpoDocumento", []) or []:
                detalles_pdf.append(
                    {
                        "cantidad": float(d.get("cantidad", 1)),
                        "descripcion": d.get("descripcion", ""),
                        "precio_unitario": float(d.get("precioUni", 0)),
                        "ventas_gravadas": float(d.get("ventaGravada", 0)),
                        "ventas_exentas": float(d.get("ventaExenta", 0)),
                        "ventas_no_sujetas": float(d.get("ventaNoSuj", 0)),
                    }
                )

        cliente = data.get("receptor", {}) or {}
        distribuidor = {}

        conf = {
            "debito": (NOTAS_DEBITO_DIR, "NotaDebito", generar_nota_debito_pdf),
            "credito": (NOTAS_CREDITO_DIR, "NotaCredito", generar_nota_credito_pdf),
            "remision": (NOTAS_REMISION_DIR, "NotaRemision", generar_nota_remision_pdf),
        }
        out_dir, doc_type, pdf_func = conf.get(tipo)
        os.makedirs(out_dir, exist_ok=True)
        pdf_path, json_path = get_dte_document_paths(
            nota_json["identificacion"].get("fecEmi"),
            cliente.get("nombre") or cliente.get("nombreComercial") or "",
            nota_json["identificacion"].get("numeroControl"),
            doc_type,
        )
        pdf_func(
            venta_data,
            detalles_pdf,
            cliente or {},
            distribuidor or {},
            archivo=str(pdf_path),
        )

        # Guardar JSON sin firmar para permitir vista previa
        save_file(json_path, stable_stringify(nota_json, indent=2))

        # Mostrar previsualización del PDF generado
        try:
            self._show_pdf_preview(pdf_path)
        except Exception:
            pass

        # Permitir al usuario ver PDF/JSON antes de firmar
        while True:
            msg = QMessageBox(self)
            msg.setWindowTitle("Firmar nota")
            msg.setText("¿Desea firmar y transmitir la nota?")
            btn_firmar = msg.addButton("Firmar", QMessageBox.AcceptRole)
            btn_pdf = msg.addButton("Ver PDF", QMessageBox.ActionRole)
            btn_json = msg.addButton("Ver JSON", QMessageBox.ActionRole)
            msg.addButton(QMessageBox.Cancel)
            msg.exec_()
            clicked = msg.clickedButton()
            if clicked == btn_pdf:
                QDesktopServices.openUrl(QUrl.fromLocalFile(pdf_path))
                continue
            if clicked == btn_json:
                QDesktopServices.openUrl(QUrl.fromLocalFile(json_path))
                continue
            if clicked == btn_firmar:
                break
            return

        sign_and_save(nota_json, json_path)

        try:
            if tipo == "debito":
                resp = enviar_nota_debito(self.manager.db, nota_id)
            elif tipo == "credito":
                resp = enviar_nota_credito(self.manager.db, nota_id)
            else:
                resp = None
            if resp and resp.get("estado") == "Error":
                QMessageBox.critical(self, "Nota", resp.get("detalle", "Error"))
            else:
                QMessageBox.information(self, "Nota", "Nota registrada y transmitida")
        except dte.DTEValidationError as exc:
            self._show_validation_errors(exc.errors, exc.json_path)
        except Exception as exc:
            QMessageBox.critical(self, "Nota", str(exc))
        self.load_invoices()

    def delete_files(self):
        """Elimina PDF y JSON asociados a la venta seleccionada."""
        data = self._selected_entry()
        if not data:
            QMessageBox.warning(self, "Eliminar", "Seleccione una venta")
            return
        paths = []
        pdf_path = None
        ticket_path = None
        row_type = data.get("row_type")
        if row_type in ("venta", "ticket"):
            venta_id = data.get("id")
            if row_type == "venta":
                pdf_path = self.manager.db.get_factura_pdf(venta_id)
                if pdf_path:
                    paths.append(pdf_path)
                    paths.append(os.path.splitext(pdf_path)[0] + ".json")
                ticket_path = self.manager.db.get_ticket_pdf(venta_id)
                if ticket_path:
                    paths.append(ticket_path)
                    paths.append(os.path.splitext(ticket_path)[0] + ".json")
            else:
                ticket_path = data.get("pdf")
                if ticket_path:
                    paths.append(ticket_path)
                    json_path = data.get("json") or os.path.splitext(ticket_path)[0] + ".json"
                    paths.append(json_path)
        else:
            for p in [data.get("pdf"), data.get("json")]:
                if p:
                    paths.append(p)
        paths = [p for p in paths if os.path.exists(p)]
        if not paths:
            if row_type in ("venta", "ticket"):
                confirm = QMessageBox.question(
                    self,
                    "Eliminar",
                    "No se encontraron archivos. ¿Eliminar registros?",
                    QMessageBox.Yes | QMessageBox.No,
                )
                if confirm == QMessageBox.Yes:
                    if row_type == "venta" and pdf_path:
                        self.manager.db.delete_factura_pdf(venta_id)
                    if ticket_path:
                        self.manager.db.delete_ticket_pdf(venta_id)
                    QMessageBox.information(self, "Eliminar", "Registros eliminados")
                    self.load_invoices()
                else:
                    QMessageBox.information(self, "Eliminar", "No se eliminaron registros")
            else:
                QMessageBox.information(self, "Eliminar", "No se encontraron archivos")
            return
        confirm = QMessageBox.question(
            self,
            "Eliminar",
            "¿Eliminar archivos?",
            QMessageBox.Yes | QMessageBox.No,
        )
        if confirm != QMessageBox.Yes:
            return
        for p in paths:
            try:
                os.remove(p)
            except OSError:
                pass
        if row_type == "venta":
            if pdf_path:
                self.manager.db.delete_factura_pdf(venta_id)
            if ticket_path:
                self.manager.db.delete_ticket_pdf(venta_id)
        elif row_type == "ticket":
            if ticket_path:
                self.manager.db.delete_ticket_pdf(venta_id)
        QMessageBox.information(self, "Eliminar", "Archivos eliminados")
        self.load_invoices()

    # ------------------------------------------------------------------
    # Previsualización de facturas
    # ------------------------------------------------------------------
    def show_invoice(self):
        if self.table.currentRow() < 0:
            self.preview_label.setText("Previsualización del PDF")
            self._clear_preview_files()
            return
        data = self._selected_entry()
        if not data:
            self.preview_label.setText("Previsualización del PDF")
            self._clear_preview_files()
            return
        if data.get("row_type") == "venta":
            self._update_preview(data.get("id"))
        else:
            pdf = data.get("pdf")
            if pdf and os.path.exists(pdf):
                self._show_pdf_preview(pdf)
            else:
                self.preview_label.setText("No hay PDF")
                self._clear_preview_files()

    def _clear_preview_files(self):
        """Remove temporary preview image without deleting stored PDFs."""
        img = getattr(self, "preview_image_file", None)
        if img and os.path.exists(img):
            try:
                os.remove(img)
            except OSError:
                pass
        self.preview_pdf_file = None
        self.preview_image_file = None

    def _show_pdf_preview(self, pdf_path):
        self._clear_preview_files()
        prefix = tempfile.mktemp()
        try:
            png_path = prefix + ".png"
            if shutil.which("pdftoppm"):
                subprocess.run([
                    "pdftoppm",
                    "-png",
                    "-singlefile",
                    pdf_path,
                    prefix,
                ], check=True)
            else:
                import fitz

                doc = fitz.open(pdf_path)
                page = doc.load_page(0)
                pix = page.get_pixmap()
                pix.save(png_path)

            self.preview_pdf_file = pdf_path
            self.preview_image_file = png_path
            pixmap = QPixmap(png_path)
            if pixmap.isNull():
                raise RuntimeError("failed to load image")
            scaled = pixmap.scaled(
                int(self.preview_label.width() * 0.9),
                int(self.preview_label.height() * 0.9),
                Qt.KeepAspectRatio,
                Qt.SmoothTransformation,
            )
            self.preview_label.setPixmap(scaled)
            self.preview_label.setText("")
        except Exception:
            self.preview_label.setText("No se pudo generar previsualización")
            self._clear_preview_files()

    def _update_preview(self, venta_id):
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            self.preview_label.setText("Previsualización del PDF")
            return

        self._clear_preview_files()

        is_ticket = not venta.get("cliente_id") and not self.manager.db.get_venta_credito_fiscal(venta_id)
        if is_ticket:
            pdf_path = self.manager.db.get_ticket_pdf(venta_id)
            if not pdf_path or not os.path.exists(pdf_path):
                pdf_path = self._generate_ticket_pdf(venta_id)
        else:
            pdf_path = self.manager.db.get_factura_pdf(venta_id)
            if not pdf_path or not os.path.exists(pdf_path):
                pdf_path = self._generate_invoice_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            self.preview_label.setText("No se pudo generar previsualización")
            return

        self._show_pdf_preview(pdf_path)

    def _generate_invoice_pdf(self, venta_id):
        return generate_invoice_pdf(self.manager, venta_id)

    def _generate_ticket_pdf(self, venta_id):
        """Generate and store the ticket PDF for the given sale."""
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            return None

        detalles = self.manager.db.get_detalles_venta(venta_id)
        extra = {}
        raw_extra = venta.get("extra") if venta else None
        if raw_extra:
            try:
                extra = json.loads(raw_extra)
            except Exception:
                extra = {}

        cliente = None
        if venta.get("cliente_id"):
            cliente = next((c for c in self.manager._clientes if c["id"] == venta["cliente_id"]), None)
        cliente_nombre = cliente.get("nombre") if cliente else ""

        filename, json_path = get_document_paths(
            venta.get("fecha"), cliente_nombre, venta_id, "Ticket"
        )

        generar_ticket_personalizado(venta, detalles, filename, dte_data=extra)
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump({"venta": venta, "detalles": detalles}, fh, ensure_ascii=False, indent=2)
        self.manager.db.add_ticket_pdf(venta_id, filename)
        return filename

    def _send_ticket_email(self, venta_id):
        venta = next((v for v in self.manager.db.get_ventas() if v["id"] == venta_id), None)
        if not venta:
            QMessageBox.warning(self, "Enviar ticket", "No se encontró la venta seleccionada.")
            return

        cliente_email = ""
        if venta.get("cliente_id"):
            cli = next((c for c in self.manager._clientes if c["id"] == venta["cliente_id"]), None)
            if cli:
                cliente_email = cli.get("email", "")
        if not cliente_email:
            QMessageBox.warning(self, "Enviar ticket", "El cliente no tiene correo registrado.")
            return

        pdf_path = self.manager.db.get_ticket_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            pdf_path = self._generate_ticket_pdf(venta_id)
        if not pdf_path or not os.path.exists(pdf_path):
            QMessageBox.warning(self, "Enviar ticket", "No se pudo generar el ticket.")
            return
        json_path = os.path.splitext(pdf_path)[0] + ".json"
        if not os.path.exists(json_path):
            pdf_path = self._generate_ticket_pdf(venta_id)
            json_path = os.path.splitext(pdf_path)[0] + ".json"
            if not os.path.exists(json_path):
                QMessageBox.warning(self, "Enviar ticket", "No se encontró el JSON firmado.")
                return

        creds = {}
        if os.path.exists(DATOS_NEGOCIO_PATH):
            try:
                with open(DATOS_NEGOCIO_PATH, "r", encoding="utf-8") as f:
                    creds = json.load(f)
            except Exception:
                creds = {}
        server = creds.get("smtp_server")
        port = creds.get("smtp_port")
        user = creds.get("email_usuario")
        password = os.getenv("INVENTARIO_EMAIL_PASSWORD") or creds.get("email_contrasena")
        if not all([server, port, user, password]):
            QMessageBox.warning(self, "Enviar ticket", "Credenciales SMTP incompletas.")
            return

        subject = "Ticket"
        body = (
            "Adjunto se envía la representación gráfica en PDF y el documento firmado en formato JSON"
        )

        self.btn_enviar.setEnabled(False)
        self.email_thread = EmailSender(
            server,
            port,
            user,
            password,
            cliente_email,
            subject,
            body,
            [pdf_path, json_path],
        )
        self.email_thread.finished.connect(self._on_email_sent)
        self.email_thread.start()

